// Class: ReadBDT_100_25_05_15
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_100_25_05_15
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Tue Sep 18 22:24:01 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 274422
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "15" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [5.96046447754e-06,3.14158797264]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [1.51991844177e-06,3.14158964157]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [86.8835525513,3932.9206543]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.99961078167,4.64822101593]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [0.213053271174,2188.19360352]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0001106262,1194.46325684]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39986610413,2.39999628067]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [9.05990600586e-06,3.14136242867]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_100_25_05_15Node
   
#ifndef BDT_100_25_05_15Node__def
#define BDT_100_25_05_15Node__def
   
class BDT_100_25_05_15Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_100_25_05_15Node ( BDT_100_25_05_15Node* left,BDT_100_25_05_15Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_100_25_05_15Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_100_25_05_15Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_100_25_05_15Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_100_25_05_15Node*   fLeft;     // pointer to the left daughter node
   BDT_100_25_05_15Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_100_25_05_15Node::~BDT_100_25_05_15Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_100_25_05_15Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_100_25_05_15Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_100_25_05_15 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_100_25_05_15( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_100_25_05_15" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_100_25_05_15() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_100_25_05_15Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_100_25_05_15::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_100_25_05_15Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_100_25_05_15Node*)current->GetRight();
         else current=(BDT_100_25_05_15Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_100_25_05_15::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.378442315179395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.066, 0, 1, 0.710867,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425353,-99) , 
5, 223.85, 0, 0, 0.457763,-99) , 
NN(
0, 
0, 
-1, 212.929, 0, -1, 0.281146,-99) , 
2, 288.579, 0, 0, 0.361472,-99) , 
7, 1.57058, 0, 0, 0.501157,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.302606);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.547, 0, 1, 0.741153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455665,-99) , 
3, -0.165158, 0, 0, 0.557024,-99) , 
5, 121.514, 0, 0, 0.651546,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448953,-99) , 
3, -0.0626415, 0, 0, 0.489233,-99) , 
NN(
0, 
0, 
-1, 232.181, 0, -1, 0.333458,-99) , 
2, 319.265, 0, 0, 0.392907,-99) , 
7, 1.37435, 0, 0, 0.508905,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.249267);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 156.994, 0, 1, 0.6365,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411472,-99) , 
4, 197.995, 0, 0, 0.500787,-99) , 
NN(
0, 
0, 
-1, 0.785405, 0, -1, 0.352037,-99) , 
2, 288.94, 0, 0, 0.420072,-99) , 
7, 1.37426, 0, 0, 0.518581,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.19673);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.014, 0, 1, 0.631888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481786,-99) , 
1, 0.981659, 0, 0, 0.514743,-99) , 
NN(
0, 
0, 
-1, 203.149, 0, -1, 0.399481,-99) , 
2, 319.265, 0, 0, 0.445173,-99) , 
7, 1.7669, 0, 0, 0.509442,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.19106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.592, 0, 1, 0.661929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469357,-99) , 
4, 249.839, 0, 0, 0.496406,-99) , 
5, 121.531, 0, 0, 0.573324,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45724,-99) , 
1, 0.785347, 0, 0, 0.48293,-99) , 
NN(
0, 
0, 
-1, 1.96354, 1, -1, 0.386108,-99) , 
2, 319.116, 0, 0, 0.424038,-99) , 
7, 0.981682, 0, 0, 0.511989,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.126211);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.069, 0, 1, 0.647508,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493194,-99) , 
5, 172.281, 0, 0, 0.510616,-99) , 
NN(
0, 
0, 
-1, 220.86, 0, -1, 0.385842,-99) , 
0, 0.981777, 0, 0, 0.488114,-99) , 
3, -0.00220028, 0, 0, 0.52316,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.130806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.013, 0, 1, 0.594425,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17797, 0, 1, 0.526128,-99) , 
NN(
0, 
0, 
-1, 202.427, 0, -1, 0.438221,-99) , 
2, 290.614, 0, 0, 0.479197,-99) , 
3, -0.113395, 0, 0, 0.525676,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.125282);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.004, 0, 1, 0.564881,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451234,-99) , 
3, -0.233706, 0, 0, 0.480096,-99) , 
NN(
0, 
0, 
-1, 235.113, 0, -1, 0.406919,-99) , 
0, 0.981748, 0, 0, 0.454177,-99) , 
7, 0.981616, 0, 0, 0.519394,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0940487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.981661, 0, 1, 0.653871,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17804, 0, 1, 0.516876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405431,-99) , 
2, 202.021, 0, 0, 0.453297,-99) , 
2, 271.117, 0, 0, 0.490219,-99) , 
5, 193.002, 0, 0, 0.511822,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0950708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 247.061, 0, 1, 0.68573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490163,-99) , 
7, 0.785384, 0, 0, 0.633844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490644,-99) , 
5, 135.67, 0, 0, 0.507234,-99) , 
NN(
0, 
0, 
-1, 0.981748, 0, -1, 0.453849,-99) , 
7, 0.981605, 0, 0, 0.48463,-99) , 
5, 187.085, 0, 0, 0.506284,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0851441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744026,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17809, 0, 1, 0.521942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415761,-99) , 
1, 1.37459, 1, 0, 0.458329,-99) , 
2, 263.125, 0, 0, 0.498015,-99) , 
5, 264.587, 0, 0, 0.509031,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0767562);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.679363,-99) , 
NN(
NN(
0, 
0, 
-1, 377.764, 0, 1, 0.529433,-99) , 
NN(
0, 
0, 
-1, 1.49977, 1, -1, 0.473291,-99) , 
3, -0.108272, 0, 0, 0.494169,-99) , 
5, 233.42, 0, 0, 0.507091,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0819532);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 331.659, 0, 1, 0.671535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499423,-99) , 
1, 0.589105, 0, 0, 0.5197,-99) , 
7, 1.17802, 0, 0, 0.61326,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446743,-99) , 
6, 1.20008, 1, 0, 0.50728,-99) , 
NN(
0, 
0, 
-1, -0.438633, 0, -1, 0.458303,-99) , 
7, 0.785285, 0, 0, 0.490915,-99) , 
5, 187.086, 0, 0, 0.508256,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0729881);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701127,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391363,-99) , 
0, 1.17823, 0, 0, 0.538393,-99) , 
NN(
0, 
0, 
-1, 1.20003, 1, -1, 0.482947,-99) , 
5, 143.88, 0, 0, 0.496828,-99) , 
5, 264.587, 0, 0, 0.505551,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0721373);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695708,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487399,-99) , 
5, 90.2177, 0, 0, 0.513358,-99) , 
NN(
0, 
0, 
-1, -0.368535, 0, -1, 0.430656,-99) , 
6, -1.19995, 0, 0, 0.503182,-99) , 
5, 264.504, 0, 0, 0.511433,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0620116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686906,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468108,-99) , 
6, 1.04987, 1, 0, 0.509129,-99) , 
NN(
0, 
0, 
-1, 143.837, 0, -1, 0.455424,-99) , 
6, -1.19983, 0, 0, 0.502427,-99) , 
5, 264.587, 0, 0, 0.510138,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0442863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672519,-99) , 
NN(
NN(
0, 
0, 
-1, 184.037, 0, 1, 0.509478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454422,-99) , 
7, 0.343563, 1, 0, 0.473845,-99) , 
7, 0.785296, 0, 0, 0.497728,-99) , 
5, 264.503, 0, 0, 0.504794,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0535403);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659277,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499054,-99) , 
1, 1.17809, 0, 0, 0.508906,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440913,-99) , 
2, 202.888, 0, 0, 0.469939,-99) , 
2, 254.63, 0, 0, 0.495133,-99) , 
5, 255.628, 0, 0, 0.502889,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0514828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655048,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483496,-99) , 
7, 1.17784, 0, 0, 0.49911,-99) , 
NN(
0, 
0, 
-1, 54.8195, 1, -1, 0.452218,-99) , 
5, 62.8524, 0, 0, 0.492653,-99) , 
5, 255.628, 0, 0, 0.500098,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0534175);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677375,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493861,-99) , 
3, -0.037143, 0, 0, 0.523426,-99) , 
NN(
0, 
0, 
-1, -0.899972, 0, -1, 0.48384,-99) , 
7, 1.96322, 0, 0, 0.495151,-99) , 
5, 264.587, 0, 0, 0.502882,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0379996);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694426,-99) , 
NN(
NN(
0, 
0, 
-1, -0.0187328, 0, 1, 0.538977,-99) , 
NN(
0, 
0, 
-1, -1.19995, 0, -1, 0.492003,-99) , 
5, 157.373, 0, 0, 0.50174,-99) , 
5, 295.425, 0, 0, 0.506633,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0485602);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648886,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456358,-99) , 
2, 237.654, 0, 0, 0.527459,-99) , 
NN(
0, 
0, 
-1, -1.49989, 0, -1, 0.489391,-99) , 
5, 143.88, 0, 0, 0.49939,-99) , 
5, 264.587, 0, 0, 0.505359,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0663578);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495814,-99) , 
7, 1.17805, 0, 0, 0.623826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460566,-99) , 
6, 1.36862, 1, 0, 0.517588,-99) , 
NN(
0, 
0, 
-1, 246.677, 0, -1, 0.476073,-99) , 
6, -0.899871, 0, 0, 0.509325,-99) , 
5, 233.419, 0, 0, 0.516908,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0587519);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651564,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17809, 0, 1, 0.517657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449515,-99) , 
1, 1.37453, 1, 0, 0.479125,-99) , 
2, 239.704, 0, 0, 0.505775,-99) , 
4, 443.712, 0, 0, 0.511014,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0256963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674003,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578985,-99) , 
NN(
0, 
0, 
-1, 102.671, 0, -1, 0.494094,-99) , 
4, 406.284, 0, 0, 0.497199,-99) , 
5, 294.915, 0, 0, 0.501759,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0354968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643354,-99) , 
NN(
NN(
0, 
0, 
-1, 0.392715, 1, 1, 0.556576,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497461,-99) , 
1, 0.785394, 0, 0, 0.506675,-99) , 
5, 210.937, 0, 0, 0.50945,-99) , 
5, 264.588, 0, 0, 0.514985,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.041184);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37438, 0, 1, 0.602607,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57714,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481216,-99) , 
2, 218.621, 0, 0, 0.503479,-99) , 
4, 405.422, 0, 0, 0.505603,-99) , 
5, 233.686, 0, 0, 0.511669,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0368849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.40515, 1, 1, 0.623195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488797,-99) , 
7, 1.17803, 0, 0, 0.571372,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463034,-99) , 
4, 128.135, 0, 0, 0.498672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427741,-99) , 
6, -1.79997, 0, 0, 0.496002,-99) , 
5, 193.058, 0, 0, 0.505782,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0358581);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620348,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494206,-99) , 
3, 0.0149954, 0, 0, 0.500257,-99) , 
NN(
0, 
0, 
-1, -1.72487, 0, -1, 0.435651,-99) , 
6, -1.49986, 0, 0, 0.495644,-99) , 
5, 264.587, 0, 0, 0.500647,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0212197);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450935,-99) , 
6, 1.80002, 1, 0, 0.49968,-99) , 
4, 405.422, 0, 0, 0.501496,-99) , 
5, 264.588, 0, 0, 0.506858,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0260877);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619758,-99) , 
NN(
NN(
0, 
0, 
-1, 404.963, 0, 1, 0.505192,-99) , 
NN(
0, 
0, 
-1, 0.981579, 1, -1, 0.447692,-99) , 
6, -1.49973, 0, 0, 0.501099,-99) , 
5, 264.588, 0, 0, 0.505896,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0225629);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624948,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468885,-99) , 
5, 63.4066, 0, 0, 0.495633,-99) , 
4, 404.336, 0, 0, 0.497746,-99) , 
5, 264.503, 0, 0, 0.502874,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0596477);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63698,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491444,-99) , 
1, 1.17809, 0, 0, 0.503586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449724,-99) , 
7, 0.381448, 1, 0, 0.462232,-99) , 
2, 234.443, 0, 0, 0.491662,-99) , 
4, 443.758, 0, 0, 0.496966,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0440325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626201,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17809, 0, 1, 0.512439,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442281,-99) , 
2, 192.608, 0, 0, 0.476691,-99) , 
2, 273.152, 0, 0, 0.498156,-99) , 
5, 264.503, 0, 0, 0.503385,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.032734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612936,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461288,-99) , 
6, -1.36848, 0, 0, 0.498927,-99) , 
NN(
0, 
0, 
-1, 0.980785, 1, -1, 0.47342,-99) , 
6, 0.899826, 1, 0, 0.493728,-99) , 
5, 255.627, 0, 0, 0.499313,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0232236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548964,-99) , 
NN(
0, 
0, 
-1, 200.337, 0, -1, 0.494057,-99) , 
2, 691.969, 0, 0, 0.496125,-99) , 
5, 264.587, 0, 0, 0.50063,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0455299);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624354,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489393,-99) , 
6, -0.900007, 0, 0, 0.513629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482674,-99) , 
5, 184.115, 0, 0, 0.491886,-99) , 
4, 221.492, 1, 0, 0.503273,-99) , 
5, 264.588, 0, 0, 0.508112,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0189459);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604324,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562171,-99) , 
NN(
0, 
0, 
-1, 1.80001, 1, -1, 0.496238,-99) , 
4, 406.627, 0, 0, 0.498399,-99) , 
5, 264.588, 0, 0, 0.502474,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0426071);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493986,-99) , 
1, 0.1322, 1, 0, 0.523086,-99) , 
0, 2.55268, 1, 0, 0.553906,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49877,-99) , 
1, 1.17809, 0, 0, 0.509,-99) , 
NN(
0, 
0, 
-1, 111.229, 1, -1, 0.470714,-99) , 
2, 232.181, 0, 0, 0.497172,-99) , 
2, 551.488, 0, 0, 0.503246,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0251314);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587739,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499684,-99) , 
2, 491.203, 0, 0, 0.504137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445533,-99) , 
6, 1.79974, 1, 0, 0.501855,-99) , 
3, 0.134848, 0, 0, 0.50815,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0560242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639472,-99) , 
NN(
NN(
0, 
0, 
-1, 426.318, 0, 1, 0.529962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470826,-99) , 
7, 0.588878, 0, 0, 0.495925,-99) , 
3, -0.237634, 0, 0, 0.516193,-99) , 
5, 295.426, 0, 0, 0.519254,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0228765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601227,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498179,-99) , 
3, 0.0666398, 0, 0, 0.50271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431854,-99) , 
4, 81.2548, 0, 0, 0.500653,-99) , 
5, 264.504, 0, 0, 0.50466,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0351581);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594801,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496397,-99) , 
7, 1.57059, 1, 0, 0.510074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457221,-99) , 
0, 0.392861, 0, 0, 0.507622,-99) , 
5, 264.587, 0, 0, 0.511099,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0352894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596971,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479952,-99) , 
0, 0.981745, 0, 0, 0.507256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458853,-99) , 
6, 1.79963, 1, 0, 0.505372,-99) , 
5, 264.587, 0, 0, 0.509055,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0311541);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481856,-99) , 
2, 248.223, 0, 0, 0.498092,-99) , 
NN(
0, 
0, 
-1, 84.7385, 0, -1, 0.447835,-99) , 
4, 112.374, 0, 0, 0.494722,-99) , 
5, 264.504, 0, 0, 0.498457,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0219637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583261,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436018,-99) , 
4, 81.0377, 0, 0, 0.502131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438007,-99) , 
6, 1.79943, 1, 0, 0.499689,-99) , 
5, 264.588, 0, 0, 0.50303,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0410147);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58631,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43832,-99) , 
4, 82.1085, 0, 0, 0.527707,-99) , 
NN(
0, 
0, 
-1, -1.7998, 0, -1, 0.489909,-99) , 
4, 163.095, 1, 0, 0.498754,-99) , 
5, 264.503, 0, 0, 0.502209,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0344657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595689,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487123,-99) , 
2, 235.67, 0, 0, 0.506119,-99) , 
4, 466.05, 0, 0, 0.508573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447149,-99) , 
4, 98.2838, 0, 0, 0.506003,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0310789);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554985,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497678,-99) , 
5, 214.275, 0, 0, 0.501534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475381,-99) , 
1, 0.196358, 1, 0, 0.480985,-99) , 
6, 0.000358582, 1, 0, 0.491324,-99) , 
3, 0.176029, 0, 0, 0.49471,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0251054);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569098,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0613466, 1, 1, 0.532068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478398,-99) , 
7, 0.748529, 0, 0, 0.49748,-99) , 
7, 0.196328, 1, 0, 0.50008,-99) , 
5, 264.503, 0, 0, 0.502833,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0470048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563505,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485025,-99) , 
2, 202.217, 0, 0, 0.522254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47868,-99) , 
1, 0.294502, 1, 0, 0.488118,-99) , 
1, 1.57079, 0, 0, 0.496873,-99) , 
5, 264.587, 0, 0, 0.499437,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0373736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 375.225, 0, 1, 0.515653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482184,-99) , 
5, 172.28, 0, 0, 0.489934,-99) , 
0, 2.35619, 1, 0, 0.501327,-99) , 
NN(
0, 
0, 
-1, 1.76715, 0, -1, 0.446659,-99) , 
4, 110.853, 0, 0, 0.498199,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0397617);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443411,-99) , 
7, 1.37433, 0, 0, 0.546722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484099,-99) , 
4, 232.804, 1, 0, 0.499769,-99) , 
5, 234.07, 0, 0, 0.50286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438586,-99) , 
6, 1.79974, 1, 0, 0.500409,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0201499);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577555,-99) , 
NN(
0, 
0, 
-1, -1.49989, 0, -1, 0.492162,-99) , 
4, 448.723, 0, 0, 0.4949,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.036586);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 336.46, 0, 1, 0.535583,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486894,-99) , 
6, 0.900057, 1, 0, 0.506342,-99) , 
NN(
0, 
0, 
-1, 107.28, 1, -1, 0.479944,-99) , 
6, -0.599892, 0, 0, 0.498749,-99) , 
3, 0.0629033, 0, 0, 0.503505,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0480058);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 325.459, 0, 1, 0.525805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480209,-99) , 
7, 1.17797, 0, 0, 0.50045,-99) , 
1, 0.785395, 0, 0, 0.509695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449071,-99) , 
4, 111.649, 1, 0, 0.504492,-99) , 
NN(
0, 
0, 
-1, 0.00206614, 1, -1, 0.425803,-99) , 
1, 0.981624, 1, 0, 0.469529,-99) , 
4, 136.962, 0, 0, 0.504985,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0542056);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.46637, 1, 1, 0.569644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447233,-99) , 
7, 0.981645, 0, 0, 0.529607,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482493,-99) , 
1, 0.589037, 0, 0, 0.507825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478574,-99) , 
3, -0.502325, 1, 0, 0.482044,-99) , 
7, 0.981532, 1, 0, 0.493154,-99) , 
4, 333.556, 0, 0, 0.497802,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0232181);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496722,-99) , 
4, 112.708, 0, 0, 0.535548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497848,-99) , 
5, 264.504, 0, 0, 0.500445,-99) , 
3, -0.508543, 1, 0, 0.504773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424731,-99) , 
3, -0.24823, 0, 0, 0.457119,-99) , 
7, 0.196332, 0, 0, 0.501544,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0293449);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497676,-99) , 
7, 0.110434, 1, 0, 0.542358,-99) , 
NN(
NN(
0, 
0, 
-1, 362.628, 0, 1, 0.531676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484845,-99) , 
5, 110.869, 1, 0, 0.496017,-99) , 
3, 0.063844, 0, 0, 0.500801,-99) , 
7, 0.196344, 1, 0, 0.504104,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0308167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494058,-99) , 
4, 239.858, 1, 0, 0.504948,-99) , 
3, 0.140684, 0, 0, 0.507512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529113,-99) , 
NN(
0, 
0, 
-1, 76.0002, 1, -1, 0.4567,-99) , 
1, 0.392732, 1, 0, 0.477878,-99) , 
4, 137.817, 0, 0, 0.503958,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0209856);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555473,-99) , 
NN(
NN(
0, 
0, 
-1, 208.692, 1, 1, 0.514426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459064,-99) , 
7, 1.59508, 1, 0, 0.494869,-99) , 
7, 1.9632, 0, 0, 0.500276,-99) , 
4, 411.531, 0, 0, 0.503009,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0364004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550124,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470309,-99) , 
2, 212.344, 0, 0, 0.506879,-99) , 
NN(
0, 
0, 
-1, 2.15983, 1, -1, 0.483339,-99) , 
3, -0.243738, 0, 0, 0.49729,-99) , 
4, 411.479, 0, 0, 0.499869,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0534921);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.5774, 1, 1, 0.550609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470575,-99) , 
0, 2.94535, 1, 0, 0.523661,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490341,-99) , 
1, 1.17809, 0, 0, 0.500184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460359,-99) , 
2, 135.976, 1, 0, 0.468436,-99) , 
2, 239.202, 0, 0, 0.489931,-99) , 
2, 569.538, 0, 0, 0.493123,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0282853);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56822,-99) , 
NN(
NN(
0, 
0, 
-1, 198.583, 1, 1, 0.511275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453779,-99) , 
4, 84.9966, 0, 0, 0.509551,-99) , 
4, 448.444, 0, 0, 0.511458,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0324558);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477653,-99) , 
0, 0.589122, 0, 0, 0.510019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440494,-99) , 
6, 1.91253, 1, 0, 0.507967,-99) , 
NN(
0, 
0, 
-1, 218.78, 0, -1, 0.4686,-99) , 
6, -1.49973, 0, 0, 0.505146,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0355261);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492482,-99) , 
6, -1.04974, 0, 0, 0.513851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442632,-99) , 
1, 2.88392, 0, 0, 0.473719,-99) , 
1, 2.55254, 1, 0, 0.508836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537837,-99) , 
NN(
0, 
0, 
-1, 118.772, 1, -1, 0.486731,-99) , 
5, 233.42, 0, 0, 0.490063,-99) , 
6, 0.000176787, 1, 0, 0.499527,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0207961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.57704, 0, 1, 0.507493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46209,-99) , 
1, 2.94522, 1, 0, 0.505472,-99) , 
NN(
0, 
0, 
-1, -0.212532, 0, -1, 0.469197,-99) , 
6, -1.49973, 0, 0, 0.502912,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0387501);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432941,-99) , 
7, 1.17806, 0, 0, 0.532914,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490065,-99) , 
0, 1.1781, 1, 0, 0.495757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424829,-99) , 
0, 1.96347, 0, 0, 0.46655,-99) , 
4, 120.502, 0, 0, 0.493321,-99) , 
4, 385.151, 0, 0, 0.495983,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0236805);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563533,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483357,-99) , 
5, 106.686, 1, 0, 0.526217,-99) , 
NN(
0, 
0, 
-1, 0.600048, 1, -1, 0.494635,-99) , 
1, 2.55252, 0, 0, 0.499199,-99) , 
4, 443.455, 0, 0, 0.501449,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0551703);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586395,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491492,-99) , 
7, 0.981565, 0, 0, 0.509141,-99) , 
1, 1.05575, 0, 0, 0.514383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484792,-99) , 
4, 210.663, 0, 0, 0.535127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45662,-99) , 
2, 135.966, 1, 0, 0.471026,-99) , 
2, 237.764, 0, 0, 0.489006,-99) , 
0, 1.76715, 0, 0, 0.507462,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0287285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557544,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496039,-99) , 
3, 0.0509934, 0, 0, 0.500446,-99) , 
5, 264.588, 0, 0, 0.502787,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473017,-99) , 
6, 0.601671, 0, 0, 0.494737,-99) , 
NN(
0, 
0, 
-1, 0.552194, 0, -1, 0.435105,-99) , 
5, 107.279, 1, 0, 0.47137,-99) , 
0, 0.981748, 0, 0, 0.498184,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0264825);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.220901, 0, 1, 0.554748,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483451,-99) , 
6, -1.08756, 0, 0, 0.504688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464297,-99) , 
6, 1.79974, 1, 0, 0.503103,-99) , 
0, 0.392707, 1, 0, 0.505954,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0283518);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.19427, 0, 1, 0.547025,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445841,-99) , 
7, 2.74851, 1, 0, 0.501868,-99) , 
1, 1.96339, 0, 0, 0.505838,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473964,-99) , 
6, 0.59749, 0, 0, 0.490034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386129,-99) , 
5, 149.841, 1, 0, 0.471437,-99) , 
0, 0.981781, 0, 0, 0.500752,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0171517);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457276,-99) , 
6, -1.87495, 0, 0, 0.502876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460242,-99) , 
6, 1.79923, 1, 0, 0.501246,-99) , 
NN(
0, 
0, 
-1, 1.57092, 0, -1, 0.464419,-99) , 
4, 112.029, 0, 0, 0.499029,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0539854);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.54033, 1, 1, 0.544243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49088,-99) , 
2, 364.018, 1, 0, 0.502774,-99) , 
3, -0.403983, 1, 0, 0.510841,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475747,-99) , 
2, 227.359, 0, 0, 0.50541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474791,-99) , 
2, 241.533, 1, 0, 0.484088,-99) , 
1, 1.07993, 0, 0, 0.493371,-99) , 
1, 0.392704, 1, 0, 0.499587,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0151275);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498239,-99) , 
4, 438.414, 0, 0, 0.500409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45734,-99) , 
7, 2.7487, 1, 0, 0.498907,-99) , 
NN(
0, 
0, 
-1, 0.78249, 0, -1, 0.475139,-99) , 
4, 137.817, 0, 0, 0.496002,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0381356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.37445, 1, 1, 0.51485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473984,-99) , 
1, 2.94524, 1, 0, 0.513005,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475307,-99) , 
0, 2.35621, 1, 0, 0.513138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467871,-99) , 
7, 2.15928, 0, 0, 0.482693,-99) , 
3, -0.283803, 1, 0, 0.493804,-99) , 
6, 0.599759, 1, 0, 0.507352,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0413377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493634,-99) , 
5, 88.271, 1, 0, 0.520546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403131,-99) , 
5, 172.46, 1, 0, 0.508045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485893,-99) , 
7, 0.392681, 1, 0, 0.489843,-99) , 
1, 1.16493, 0, 0, 0.493329,-99) , 
0, 1.5708, 1, 0, 0.496919,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0285227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543257,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478207,-99) , 
0, 0.589056, 0, 0, 0.506972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470156,-99) , 
7, 0.588993, 1, 0, 0.483243,-99) , 
6, -1.20002, 0, 0, 0.504097,-99) , 
4, 411.201, 0, 0, 0.506052,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.042327);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.6998, 0, 1, 0.553172,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477715,-99) , 
0, 2.16021, 0, 0, 0.50428,-99) , 
1, 2.35616, 0, 0, 0.508478,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479486,-99) , 
2, 414.486, 0, 0, 0.486982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424854,-99) , 
0, 2.94524, 1, 0, 0.479933,-99) , 
3, -0.239959, 0, 0, 0.497322,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.031937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589319,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487492,-99) , 
1, 0.785393, 1, 0, 0.509281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489841,-99) , 
1, 2.74888, 0, 0, 0.49172,-99) , 
4, 180.409, 1, 0, 0.496739,-99) , 
0, 0.196359, 1, 0, 0.499348,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0237335);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493557,-99) , 
1, 0.785273, 0, 0, 0.54035,-99) , 
NN(
NN(
0, 
0, 
-1, 210.203, 0, 1, 0.508951,-99) , 
NN(
0, 
0, 
-1, 1.59518, 1, -1, 0.491082,-99) , 
7, 1.96336, 0, 0, 0.49625,-99) , 
6, -1.49973, 1, 0, 0.499571,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0275689);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.578658, 1, 1, 0.5114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456589,-99) , 
4, 84.8171, 0, 0, 0.509668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441383,-99) , 
7, 2.74851, 1, 0, 0.507645,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0255207);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497113,-99) , 
7, 0.392696, 1, 0, 0.500644,-99) , 
1, 2.74888, 0, 0, 0.503589,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493263,-99) , 
6, 0.300994, 0, 0, 0.510009,-99) , 
NN(
0, 
0, 
-1, 0.488958, 1, -1, 0.459622,-99) , 
7, 0.782328, 0, 0, 0.4822,-99) , 
3, -0.411791, 0, 0, 0.499375,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0261575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.171786, 1, 1, 0.51113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460884,-99) , 
7, 2.74851, 1, 0, 0.509686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456823,-99) , 
6, 1.79976, 1, 0, 0.507755,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0368991);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491135,-99) , 
6, -0.000520825, 0, 0, 0.514723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49065,-99) , 
5, 255.629, 0, 0, 0.493396,-99) , 
4, 201.49, 1, 0, 0.499016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474092,-99) , 
4, 168.629, 0, 0, 0.486054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425586,-99) , 
0, 2.74889, 1, 0, 0.473891,-99) , 
3, -0.407973, 0, 0, 0.493959,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0383427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.20008, 1, 1, 0.521298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451356,-99) , 
1, 0.196355, 0, 0, 0.49535,-99) , 
4, 222.29, 1, 0, 0.512913,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496091,-99) , 
1, 0.97995, 0, 0, 0.504189,-99) , 
NN(
0, 
0, 
-1, 2.64516, 1, -1, 0.427787,-99) , 
0, 1.1781, 0, 0, 0.493954,-99) , 
5, 118.543, 1, 0, 0.505005,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0271098);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.662263, 0, 1, 0.553976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485648,-99) , 
7, 1.7669, 1, 0, 0.525725,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487473,-99) , 
3, -0.228378, 0, 0, 0.49868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419932,-99) , 
4, 82.9012, 0, 0, 0.496467,-99) , 
2, 568.142, 0, 0, 0.499316,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.025174);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478539,-99) , 
6, 0.299677, 1, 0, 0.50481,-99) , 
0, 2.55356, 1, 0, 0.526177,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551036,-99) , 
NN(
0, 
0, 
-1, 170.939, 0, -1, 0.492492,-99) , 
2, 145.405, 1, 0, 0.495047,-99) , 
2, 553.947, 0, 0, 0.498385,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0330562);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.40516, 1, 1, 0.532153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408784,-99) , 
5, 172.281, 1, 0, 0.462522,-99) , 
7, 0.785365, 0, 0, 0.514447,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494571,-99) , 
0, 1.17813, 1, 0, 0.499475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458868,-99) , 
3, 0.0683247, 1, 0, 0.496656,-99) , 
4, 288.916, 0, 0, 0.500684,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0425603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486512,-99) , 
1, 0.932698, 1, 0, 0.496447,-99) , 
2, 351.302, 0, 0, 0.507615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478085,-99) , 
4, 270.496, 1, 0, 0.499459,-99) , 
NN(
0, 
0, 
-1, 131.36, 0, -1, 0.46167,-99) , 
6, 1.20008, 1, 0, 0.494439,-99) , 
1, 0.785396, 0, 0, 0.499469,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0225534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489919,-99) , 
3, -0.434528, 0, 0, 0.533819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481142,-99) , 
4, 313.39, 1, 0, 0.526453,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499548,-99) , 
0, 0.392742, 1, 0, 0.501857,-99) , 
NN(
0, 
0, 
-1, 0.58905, 1, -1, 0.461547,-99) , 
6, -0.693884, 0, 0, 0.499013,-99) , 
6, -0.900111, 1, 0, 0.504537,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0435726);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480022,-99) , 
0, 0.785401, 0, 0, 0.552541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423718,-99) , 
5, 156.331, 1, 0, 0.503265,-99) , 
2, 223.618, 0, 0, 0.524773,-99) , 
NN(
NN(
0, 
0, 
-1, 214.275, 0, 1, 0.508643,-99) , 
NN(
0, 
0, 
-1, 0.245435, 1, -1, 0.473774,-99) , 
2, 582.353, 1, 0, 0.504423,-99) , 
1, 0.785399, 0, 0, 0.512292,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0325868);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 265.954, 1, 1, 0.540533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497331,-99) , 
7, 1.57023, 1, 0, 0.522394,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494643,-99) , 
0, 2.35619, 0, 0, 0.510513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482199,-99) , 
5, 90.235, 0, 0, 0.493141,-99) , 
5, 121.529, 0, 0, 0.500213,-99) , 
6, 1.20004, 0, 0, 0.503177,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0286711);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49982,-99) , 
7, 1.57057, 1, 0, 0.509671,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422465,-99) , 
3, -0.213076, 0, 0, 0.469178,-99) , 
6, -1.49979, 0, 0, 0.506905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420277,-99) , 
6, 0.301246, 0, 0, 0.460516,-99) , 
0, 0.589085, 0, 0, 0.503385,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.047077);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492571,-99) , 
6, -1.19962, 1, 0, 0.499303,-99) , 
2, 386.058, 0, 0, 0.511942,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487749,-99) , 
2, 290.621, 1, 0, 0.512043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471576,-99) , 
1, 0.14725, 1, 0, 0.482993,-99) , 
2, 348.521, 1, 0, 0.495633,-99) , 
1, 0.785395, 0, 0, 0.50194,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.039651);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483035,-99) , 
2, 198.163, 0, 0, 0.504026,-99) , 
2, 383.482, 0, 0, 0.512079,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536351,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484623,-99) , 
2, 291.3, 1, 0, 0.490606,-99) , 
5, 233.42, 0, 0, 0.494139,-99) , 
1, 0.785404, 0, 0, 0.500975,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0531113);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451103,-99) , 
4, 139.634, 0, 0, 0.566029,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489142,-99) , 
1, 3.0189, 0, 0, 0.50836,-99) , 
2, 220.711, 0, 0, 0.527574,-99) , 
NN(
NN(
0, 
0, 
-1, 418.382, 0, 1, 0.518517,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485887,-99) , 
3, -0.527176, 1, 0, 0.493571,-99) , 
3, -0.0590958, 0, 0, 0.502654,-99) , 
1, 1.1781, 0, 0, 0.509436,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0438505);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.78353, 0, 1, 0.588067,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454696,-99) , 
7, 1.08194, 1, 0, 0.511297,-99) , 
2, 235.113, 0, 0, 0.533586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489823,-99) , 
5, 121.53, 0, 0, 0.497674,-99) , 
7, 0.196363, 1, 0, 0.500468,-99) , 
1, 1.17809, 0, 0, 0.509519,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0395868);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 65.217, 1, 1, 0.523348,-99) , 
NN(
0, 
0, 
-1, -0.000252843, 1, -1, 0.447562,-99) , 
5, 171.735, 1, 0, 0.51289,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495087,-99) , 
5, 187.094, 0, 0, 0.501924,-99) , 
NN(
0, 
0, 
-1, 221.937, 0, -1, 0.470178,-99) , 
6, 0.899823, 1, 0, 0.495375,-99) , 
7, 0.981616, 1, 0, 0.502738,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_100_25_05_15::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_100_25_05_15::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
