// Class: ReadBDT_50_25_05_20
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_50_25_05_20
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Tue Sep 18 22:10:06 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 274422
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [1.04904174805e-05,3.14159083366]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [1.51991844177e-06,3.14156723022]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [86.8835525513,6687.15380859]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.99961078167,4.64822101593]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [0.213053271174,1770.44580078]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0001945496,1194.01318359]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39999055862,2.39996170998]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [6.31809234619e-06,3.14115262032]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_50_25_05_20Node
   
#ifndef BDT_50_25_05_20Node__def
#define BDT_50_25_05_20Node__def
   
class BDT_50_25_05_20Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_50_25_05_20Node ( BDT_50_25_05_20Node* left,BDT_50_25_05_20Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_50_25_05_20Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_50_25_05_20Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_50_25_05_20Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_50_25_05_20Node*   fLeft;     // pointer to the left daughter node
   BDT_50_25_05_20Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_50_25_05_20Node::~BDT_50_25_05_20Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_50_25_05_20Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_50_25_05_20Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_50_25_05_20 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_50_25_05_20( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_50_25_05_20" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_50_25_05_20() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_50_25_05_20Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_50_25_05_20::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_50_25_05_20Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_50_25_05_20Node*)current->GetRight();
         else current=(BDT_50_25_05_20Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_50_25_05_20::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.374493412852042);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 208.248, 0, 1, 0.816483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493912,-99) , 
4, 190.067, 0, 0, 0.638886,-99) , 
5, 158.956, 0, 0, 0.697167,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366333,-99) , 
5, 142.752, 0, 0, 0.431769,-99) , 
NN(
0, 
0, 
-1, 0.897562, 0, -1, 0.282607,-99) , 
2, 257.239, 0, 0, 0.360977,-99) , 
7, 1.49571, 0, 0, 0.501885,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.310105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.522, 0, 1, 0.675773,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409863,-99) , 
3, -0.0439869, 0, 0, 0.443325,-99) , 
NN(
0, 
0, 
-1, 1.64608, 1, -1, 0.320631,-99) , 
2, 249.275, 0, 0, 0.388318,-99) , 
7, 1.49555, 0, 0, 0.507568,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.233893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.522, 0, 1, 0.621991,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392665,-99) , 
3, -0.232841, 0, 0, 0.445219,-99) , 
NN(
0, 
0, 
-1, 1.64544, 0, -1, 0.34109,-99) , 
2, 239.292, 0, 0, 0.401228,-99) , 
7, 1.19663, 0, 0, 0.512874,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.218223);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 167.506, 0, 1, 0.625425,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4056,-99) , 
2, 239.737, 0, 0, 0.511881,-99) , 
NN(
0, 
0, 
-1, 0.94013, 0, -1, 0.393938,-99) , 
3, -0.12776, 0, 0, 0.424006,-99) , 
7, 1.64537, 0, 0, 0.499355,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.172119);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 199.286, 0, 1, 0.61595,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466008,-99) , 
1, 1.19675, 0, 0, 0.493118,-99) , 
NN(
0, 
0, 
-1, 1.49611, 1, -1, 0.388524,-99) , 
2, 234.118, 0, 0, 0.454826,-99) , 
7, 1.94453, 0, 0, 0.502703,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.161732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.568, 0, 1, 0.697028,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452725,-99) , 
5, 83.1717, 0, 0, 0.518342,-99) , 
5, 149.522, 0, 0, 0.579927,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467908,-99) , 
4, 375.429, 0, 0, 0.477435,-99) , 
NN(
0, 
0, 
-1, -0.462067, 0, -1, 0.382335,-99) , 
0, 1.0472, 0, 0, 0.449648,-99) , 
7, 1.34621, 0, 0, 0.509696,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.119735);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 241.934, 0, 1, 0.742945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487672,-99) , 
7, 0.897476, 0, 0, 0.67241,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49962,-99) , 
5, 135.305, 0, 0, 0.525863,-99) , 
NN(
0, 
0, 
-1, 302.503, 0, -1, 0.437685,-99) , 
7, 1.04678, 0, 0, 0.486072,-99) , 
5, 199.281, 0, 0, 0.509222,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.128816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19666, 0, 1, 0.656002,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466927,-99) , 
7, 0.897142, 0, 0, 0.517895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393635,-99) , 
1, 1.34651, 1, 0, 0.431737,-99) , 
2, 232.622, 0, 0, 0.491665,-99) , 
5, 189.953, 0, 0, 0.514645,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0945004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19664, 0, 1, 0.672339,-99) , 
NN(
NN(
0, 
0, 
-1, 1.19673, 0, 1, 0.523129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431783,-99) , 
1, 1.49611, 1, 0, 0.46517,-99) , 
2, 257.393, 0, 0, 0.500809,-99) , 
5, 199.281, 0, 0, 0.52177,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0944681);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.34609, 0, 1, 0.694792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429143,-99) , 
6, -1.2569, 0, 0, 0.511947,-99) , 
NN(
0, 
0, 
-1, 1.24853, 1, -1, 0.432824,-99) , 
2, 204.715, 0, 0, 0.494879,-99) , 
5, 235.501, 0, 0, 0.50812,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0820131);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19595, 0, 1, 0.682828,-99) , 
NN(
NN(
0, 
0, 
-1, 284.387, 0, 1, 0.558316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460984,-99) , 
5, 110.829, 0, 0, 0.479135,-99) , 
3, 0.0472604, 0, 0, 0.489757,-99) , 
5, 232.484, 0, 0, 0.503496,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0749665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485363,-99) , 
7, 0.897331, 0, 0, 0.651819,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474326,-99) , 
7, 1.19662, 0, 0, 0.532213,-99) , 
NN(
0, 
0, 
-1, 324.404, 0, -1, 0.478334,-99) , 
3, 0.0221788, 0, 0, 0.486812,-99) , 
5, 213.432, 0, 0, 0.502065,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0823185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.04716, 0, 1, 0.648763,-99) , 
NN(
NN(
0, 
0, 
-1, 0.598387, 0, 1, 0.530635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467801,-99) , 
3, -0.081827, 0, 0, 0.483713,-99) , 
2, 427.436, 0, 0, 0.493371,-99) , 
5, 213.432, 0, 0, 0.507998,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0749283);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.34624, 0, 1, 0.667077,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46371,-99) , 
6, 1.02907, 1, 0, 0.510723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444785,-99) , 
2, 306.573, 0, 0, 0.467633,-99) , 
3, -0.304116, 0, 0, 0.49613,-99) , 
5, 236.602, 0, 0, 0.50719,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0459855);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69893,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45378,-99) , 
7, 0.897476, 0, 0, 0.554201,-99) , 
NN(
0, 
0, 
-1, 85.2918, 0, -1, 0.49552,-99) , 
5, 174.51, 0, 0, 0.503909,-99) , 
5, 267.908, 0, 0, 0.511745,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0599496);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 397.859, 0, 1, 0.671806,-99) , 
NN(
NN(
0, 
0, 
-1, 201.651, 0, 1, 0.519398,-99) , 
NN(
0, 
0, 
-1, 119.432, 0, -1, 0.476153,-99) , 
3, -0.126917, 0, 0, 0.493932,-99) , 
5, 249.042, 0, 0, 0.503338,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0728215);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6762,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409676,-99) , 
6, 1.91021, 1, 0, 0.515937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435205,-99) , 
5, 163.726, 0, 0, 0.454888,-99) , 
6, -1.02834, 0, 0, 0.506091,-99) , 
5, 249.041, 0, 0, 0.515239,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.059134);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487029,-99) , 
7, 0.897477, 0, 0, 0.607961,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462974,-99) , 
7, 0.747352, 0, 0, 0.524396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472261,-99) , 
1, 0.747988, 0, 0, 0.485307,-99) , 
4, 276.872, 0, 0, 0.493481,-99) , 
5, 213.432, 0, 0, 0.503715,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0584194);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685016,-99) , 
NN(
NN(
0, 
0, 
-1, 1.04714, 0, 1, 0.514068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454144,-99) , 
2, 216.454, 0, 0, 0.476091,-99) , 
2, 256.948, 0, 0, 0.500658,-99) , 
5, 267.908, 0, 0, 0.508174,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0463944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657534,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496208,-99) , 
5, 174.472, 0, 0, 0.509801,-99) , 
NN(
0, 
0, 
-1, 195.262, 1, -1, 0.480067,-99) , 
7, 1.04706, 0, 0, 0.496713,-99) , 
5, 267.908, 0, 0, 0.50291,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0386105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459289,-99) , 
7, 1.34621, 0, 0, 0.561177,-99) , 
NN(
0, 
0, 
-1, 1.25709, 1, -1, 0.493702,-99) , 
5, 205.593, 0, 0, 0.498256,-99) , 
5, 267.907, 0, 0, 0.505916,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0331777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66653,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480587,-99) , 
7, 1.34625, 0, 0, 0.563943,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444283,-99) , 
6, -1.7138, 0, 0, 0.499959,-99) , 
5, 205.637, 0, 0, 0.504315,-99) , 
5, 267.907, 0, 0, 0.510677,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.046534);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.34624, 0, 1, 0.618307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474188,-99) , 
2, 203.817, 0, 0, 0.503701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435234,-99) , 
6, -1.71389, 0, 0, 0.50059,-99) , 
5, 235.502, 0, 0, 0.507973,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0396899);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681081,-99) , 
NN(
NN(
0, 
0, 
-1, 216.608, 0, 1, 0.50684,-99) , 
NN(
0, 
0, 
-1, 0.571866, 1, -1, 0.468819,-99) , 
7, 0.7479, 0, 0, 0.49506,-99) , 
5, 283.253, 0, 0, 0.501145,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.038821);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651106,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481652,-99) , 
7, 1.04702, 0, 0, 0.495575,-99) , 
NN(
0, 
0, 
-1, 1.34636, 0, -1, 0.440278,-99) , 
4, 124.64, 0, 0, 0.49058,-99) , 
5, 281.876, 0, 0, 0.495509,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0275748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609278,-99) , 
NN(
0, 
0, 
-1, 1.25712, 1, -1, 0.491212,-99) , 
5, 249.041, 0, 0, 0.497083,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0344628);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62128,-99) , 
NN(
0, 
0, 
-1, -0.66016, 0, -1, 0.488351,-99) , 
5, 249.042, 0, 0, 0.495112,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0448443);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4774,-99) , 
7, 1.19667, 0, 0, 0.580923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489538,-99) , 
1, 1.04718, 0, 0, 0.498278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423315,-99) , 
4, 85.2918, 0, 0, 0.495809,-99) , 
5, 213.431, 0, 0, 0.50336,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.041579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625177,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468106,-99) , 
6, 1.25712, 1, 0, 0.505277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413714,-99) , 
4, 85.2918, 0, 0, 0.502314,-99) , 
5, 249.04, 0, 0, 0.50857,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.026659);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499613,-99) , 
5, 201.649, 0, 0, 0.502551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449676,-99) , 
0, 1.49613, 1, 0, 0.46821,-99) , 
6, 1.25715, 1, 0, 0.498444,-99) , 
5, 249.042, 0, 0, 0.503953,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0550818);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477071,-99) , 
2, 204.715, 0, 0, 0.511741,-99) , 
NN(
0, 
0, 
-1, 1.02801, 1, -1, 0.478351,-99) , 
0, 2.84237, 1, 0, 0.503988,-99) , 
5, 249.042, 0, 0, 0.509075,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0520578);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617338,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486823,-99) , 
6, -1.02858, 0, 0, 0.513706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467136,-99) , 
1, 2.69261, 0, 0, 0.478653,-99) , 
6, 0.799978, 1, 0, 0.50566,-99) , 
5, 283.253, 0, 0, 0.508859,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0472305);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446848,-99) , 
7, 0.897477, 0, 0, 0.557998,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495076,-99) , 
0, 2.8424, 1, 0, 0.530156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485918,-99) , 
4, 350.513, 0, 0, 0.488467,-99) , 
2, 578.484, 0, 0, 0.491313,-99) , 
5, 212.028, 0, 0, 0.497407,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0317987);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578139,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493026,-99) , 
3, -0.26407, 1, 0, 0.5019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442761,-99) , 
6, 1.7143, 1, 0, 0.499009,-99) , 
5, 249.041, 0, 0, 0.502901,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.03837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 241.936, 0, 1, 0.613384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443943,-99) , 
7, 0.897605, 0, 0, 0.561552,-99) , 
NN(
NN(
0, 
0, 
-1, 1.34534, 1, 1, 0.542512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481545,-99) , 
6, 0.799183, 1, 0, 0.499048,-99) , 
2, 598.837, 0, 0, 0.501612,-99) , 
5, 199.281, 0, 0, 0.508334,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0378549);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615061,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457294,-99) , 
6, -1.48569, 0, 0, 0.507779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425836,-99) , 
4, 85.2918, 0, 0, 0.505237,-99) , 
5, 283.253, 0, 0, 0.508488,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0506922);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.34602, 0, 1, 0.58242,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494343,-99) , 
1, 1.49597, 0, 0, 0.502136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442139,-99) , 
1, 1.49636, 1, 0, 0.473405,-99) , 
2, 210.38, 0, 0, 0.495685,-99) , 
5, 236.602, 0, 0, 0.500947,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.045652);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615711,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498917,-99) , 
1, 1.19675, 0, 0, 0.507856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435293,-99) , 
2, 151.563, 1, 0, 0.459597,-99) , 
2, 209.944, 0, 0, 0.497426,-99) , 
5, 283.253, 0, 0, 0.500992,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0401894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610199,-99) , 
NN(
NN(
0, 
0, 
-1, 0.897478, 0, 1, 0.51674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453178,-99) , 
0, 2.69277, 1, 0, 0.484836,-99) , 
6, 1.02811, 1, 0, 0.511383,-99) , 
5, 267.907, 0, 0, 0.515141,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0416173);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593376,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463766,-99) , 
6, 1.71425, 1, 0, 0.511845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420232,-99) , 
3, -0.376557, 0, 0, 0.456845,-99) , 
1, 2.84237, 1, 0, 0.508008,-99) , 
5, 267.907, 0, 0, 0.511263,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0472011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 325.344, 0, 1, 0.549849,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48279,-99) , 
7, 0.897251, 0, 0, 0.502583,-99) , 
NN(
0, 
0, 
-1, 93.1758, 1, -1, 0.468513,-99) , 
6, -0.799804, 0, 0, 0.49497,-99) , 
3, 0.0796994, 0, 0, 0.501322,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0483472);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591058,-99) , 
NN(
NN(
0, 
0, 
-1, 288.559, 0, 1, 0.519153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471541,-99) , 
1, 0.299198, 1, 0, 0.488023,-99) , 
1, 1.04719, 0, 0, 0.497491,-99) , 
4, 449.123, 0, 0, 0.500473,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0420076);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597453,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4498,-99) , 
7, 2.69141, 1, 0, 0.507236,-99) , 
4, 422.323, 0, 0, 0.511369,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460764,-99) , 
0, 0.448768, 1, 0, 0.480123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417463,-99) , 
7, 0.298119, 0, 0, 0.466861,-99) , 
0, 1.0472, 0, 0, 0.504106,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0379686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58179,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493539,-99) , 
1, 0.897582, 0, 0, 0.502487,-99) , 
NN(
0, 
0, 
-1, 132.998, 1, -1, 0.47338,-99) , 
2, 222.044, 0, 0, 0.495025,-99) , 
5, 267.909, 0, 0, 0.498269,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0558323);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.44309, 1, 1, 0.588403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454944,-99) , 
7, 1.04703, 0, 0, 0.540999,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476984,-99) , 
1, 2.39355, 1, 0, 0.518486,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482407,-99) , 
5, 185.896, 0, 0, 0.487029,-99) , 
7, 0.448685, 1, 0, 0.49253,-99) , 
4, 337.4, 0, 0, 0.498547,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0512242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584032,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475474,-99) , 
3, -0.286666, 0, 0, 0.509831,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47775,-99) , 
2, 402.063, 0, 0, 0.486522,-99) , 
0, 2.54319, 0, 0, 0.496997,-99) , 
4, 446.281, 0, 0, 0.499956,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0303821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554342,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490826,-99) , 
3, -0.189429, 1, 0, 0.501834,-99) , 
5, 249.042, 0, 0, 0.50449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433574,-99) , 
4, 85.705, 0, 0, 0.502262,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0304656);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593459,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492616,-99) , 
7, 1.49571, 1, 0, 0.501151,-99) , 
5, 267.909, 0, 0, 0.5047,-99) , 
NN(
0, 
0, 
-1, 137.292, 1, -1, 0.459633,-99) , 
0, 0.897605, 0, 0, 0.498662,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.023088);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559622,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495672,-99) , 
1, 0.897581, 0, 0, 0.50168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445044,-99) , 
3, -0.651863, 0, 0, 0.49903,-99) , 
5, 267.907, 0, 0, 0.501316,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0198936);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 323.834, 0, 1, 0.540488,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456969,-99) , 
4, 110.182, 0, 0, 0.497737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454877,-99) , 
4, 385.107, 1, 0, 0.495761,-99) , 
3, 0.0761667, 0, 0, 0.501082,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_50_25_05_20::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_50_25_05_20::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
