// Class: ReadBDT_100_25_01_15
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_100_25_01_15
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Tue Sep 18 22:38:20 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 274422
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "15" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "1.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [5.96046447754e-06,3.14158797264]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [2.80514359474e-06,3.14159035683]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [87.0424880981,5391.02001953]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.99552065134,3.99204134941]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [1.03412163258,2188.19360352]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0013122559,1194.46325684]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39999055862,2.39999628067]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [6.31809234619e-06,3.14152240753]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_100_25_01_15Node
   
#ifndef BDT_100_25_01_15Node__def
#define BDT_100_25_01_15Node__def
   
class BDT_100_25_01_15Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_100_25_01_15Node ( BDT_100_25_01_15Node* left,BDT_100_25_01_15Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_100_25_01_15Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_100_25_01_15Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_100_25_01_15Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_100_25_01_15Node*   fLeft;     // pointer to the left daughter node
   BDT_100_25_01_15Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_100_25_01_15Node::~BDT_100_25_01_15Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_100_25_01_15Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_100_25_01_15Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_100_25_01_15 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_100_25_01_15( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_100_25_01_15" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_100_25_01_15() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_100_25_01_15Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_100_25_01_15::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_100_25_01_15Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_100_25_01_15Node*)current->GetRight();
         else current=(BDT_100_25_01_15Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_100_25_01_15::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.0738783074860262);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.502, 0, 1, 0.701275,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404142,-99) , 
3, -0.0592992, 0, 0, 0.452795,-99) , 
NN(
0, 
0, 
-1, 198.253, 0, -1, 0.301164,-99) , 
2, 309.467, 0, 0, 0.361,-99) , 
7, 1.57076, 0, 0, 0.495082,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.0684098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 121.539, 0, 1, 0.691607,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411394,-99) , 
5, 171.737, 0, 0, 0.460042,-99) , 
NN(
0, 
0, 
-1, 221.814, 0, -1, 0.317214,-99) , 
2, 301.474, 0, 0, 0.376644,-99) , 
7, 1.57068, 0, 0, 0.501633,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.0663851);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.808, 0, 1, 0.756412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483485,-99) , 
7, 1.9262, 0, 0, 0.581851,-99) , 
5, 118.545, 0, 0, 0.67502,-99) , 
NN(
0, 
0, 
-1, -0.23658, 0, -1, 0.357603,-99) , 
7, 1.37442, 0, 0, 0.502616,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0663613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.506, 0, 1, 0.663058,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400303,-99) , 
5, 171.736, 0, 0, 0.445441,-99) , 
NN(
0, 
0, 
-1, 1.96351, 1, -1, 0.300042,-99) , 
2, 299.978, 0, 0, 0.361182,-99) , 
7, 1.37435, 0, 0, 0.498318,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0648547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.808, 0, 1, 0.741416,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422743,-99) , 
4, 187.114, 0, 0, 0.55424,-99) , 
5, 118.545, 0, 0, 0.654071,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407749,-99) , 
5, 171.736, 0, 0, 0.44418,-99) , 
NN(
0, 
0, 
-1, 206.598, 0, -1, 0.31875,-99) , 
2, 299.587, 0, 0, 0.37068,-99) , 
7, 1.37442, 0, 0, 0.499181,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0610082);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.067, 0, 1, 0.672187,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416868,-99) , 
7, 0.981426, 0, 0, 0.473784,-99) , 
NN(
0, 
0, 
-1, 1.07951, 0, -1, 0.332684,-99) , 
2, 299.587, 0, 0, 0.39305,-99) , 
7, 1.57049, 0, 0, 0.504185,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0579772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.595, 0, 1, 0.744192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485708,-99) , 
3, -0.131269, 0, 0, 0.581809,-99) , 
5, 121.533, 0, 0, 0.668518,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407582,-99) , 
4, 222.744, 0, 0, 0.4884,-99) , 
NN(
0, 
0, 
-1, 1.96354, 1, -1, 0.347441,-99) , 
2, 309.858, 0, 0, 0.404769,-99) , 
7, 1.57068, 0, 0, 0.509432,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0586429);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.6, 0, 1, 0.735803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481137,-99) , 
3, -0.150127, 0, 0, 0.557121,-99) , 
5, 121.539, 0, 0, 0.648735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435206,-99) , 
5, 220.658, 0, 0, 0.462003,-99) , 
NN(
0, 
0, 
-1, 214.548, 0, -1, 0.324581,-99) , 
2, 290.146, 0, 0, 0.386418,-99) , 
7, 1.37442, 0, 0, 0.507101,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.05288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.091, 0, 1, 0.646048,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442429,-99) , 
1, 1.17799, 0, 0, 0.471387,-99) , 
NN(
0, 
0, 
-1, 198.649, 0, -1, 0.355618,-99) , 
2, 309.858, 0, 0, 0.401239,-99) , 
7, 1.37435, 0, 0, 0.511475,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0534401);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.502, 0, 1, 0.657139,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410669,-99) , 
5, 111.141, 0, 0, 0.491591,-99) , 
NN(
0, 
0, 
-1, 1.17804, 0, -1, 0.362017,-99) , 
2, 319.265, 0, 0, 0.41159,-99) , 
7, 1.57077, 0, 0, 0.509935,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0488937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.06, 0, 1, 0.630331,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441552,-99) , 
1, 1.17809, 0, 0, 0.470417,-99) , 
NN(
0, 
0, 
-1, 234.609, 0, -1, 0.360098,-99) , 
2, 301.005, 0, 0, 0.405971,-99) , 
7, 1.37418, 0, 0, 0.50774,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0474001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.094, 0, 1, 0.642475,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471519,-99) , 
1, 0.981741, 0, 0, 0.500361,-99) , 
NN(
0, 
0, 
-1, 217.663, 0, -1, 0.369668,-99) , 
2, 319.265, 0, 0, 0.419935,-99) , 
7, 1.57049, 0, 0, 0.508381,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0476303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 477.122, 0, 1, 0.785785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436343,-99) , 
2, 238.461, 0, 0, 0.569876,-99) , 
5, 193.06, 0, 0, 0.605807,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365167,-99) , 
0, 1.17816, 0, 0, 0.466472,-99) , 
NN(
0, 
0, 
-1, 0.785405, 0, -1, 0.364265,-99) , 
3, -0.236829, 0, 0, 0.402698,-99) , 
7, 1.17807, 0, 0, 0.507595,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0441088);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 172.716, 0, 1, 0.617688,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453668,-99) , 
5, 212.555, 0, 0, 0.477731,-99) , 
NN(
0, 
0, 
-1, 198.245, 0, -1, 0.370518,-99) , 
2, 309.467, 0, 0, 0.413588,-99) , 
7, 1.37435, 0, 0, 0.506076,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0438362);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.091, 0, 1, 0.653812,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488865,-99) , 
5, 150.379, 0, 0, 0.52291,-99) , 
NN(
0, 
0, 
-1, 288.728, 0, -1, 0.386538,-99) , 
7, 1.17763, 0, 0, 0.437981,-99) , 
3, -0.0592992, 0, 0, 0.507478,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0435155);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.504, 0, 1, 0.639526,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467836,-99) , 
3, -0.0595481, 0, 0, 0.508408,-99) , 
NN(
0, 
0, 
-1, 221.042, 0, -1, 0.385203,-99) , 
2, 300.236, 0, 0, 0.438694,-99) , 
7, 1.76711, 0, 0, 0.508805,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0379767);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 188.593, 0, 1, 0.694061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496455,-99) , 
4, 251.836, 0, 0, 0.532777,-99) , 
5, 121.531, 0, 0, 0.617366,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49498,-99) , 
1, 1.17806, 0, 0, 0.520402,-99) , 
NN(
0, 
0, 
-1, 203.152, 0, -1, 0.39242,-99) , 
2, 319.265, 0, 0, 0.442559,-99) , 
7, 1.57058, 0, 0, 0.511968,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0378948);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.07, 0, 1, 0.624794,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478452,-99) , 
1, 0.981739, 0, 0, 0.505867,-99) , 
NN(
0, 
0, 
-1, 212.554, 0, -1, 0.398933,-99) , 
2, 309.858, 0, 0, 0.442816,-99) , 
7, 1.76711, 0, 0, 0.505833,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0394694);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 166.899, 0, 1, 0.638297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443325,-99) , 
5, 90.2734, 0, 0, 0.515633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389942,-99) , 
3, -0.177268, 0, 0, 0.408664,-99) , 
7, 0.981531, 0, 0, 0.458762,-99) , 
3, -0.0603528, 0, 0, 0.515608,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0400269);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 255.656, 0, 1, 0.754535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479769,-99) , 
2, 225.501, 0, 0, 0.595518,-99) , 
5, 193.064, 0, 0, 0.635777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469666,-99) , 
5, 120.217, 0, 0, 0.51883,-99) , 
NN(
0, 
0, 
-1, -0.181752, 0, -1, 0.403242,-99) , 
7, 0.981619, 0, 0, 0.456982,-99) , 
3, -0.0656067, 0, 0, 0.514712,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0372361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 463.69, 0, 1, 0.771404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496043,-99) , 
3, -0.10498, 0, 0, 0.549265,-99) , 
5, 187.087, 0, 0, 0.591027,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462561,-99) , 
5, 166.155, 0, 0, 0.496038,-99) , 
NN(
0, 
0, 
-1, 233.62, 0, -1, 0.385885,-99) , 
2, 320.684, 0, 0, 0.42812,-99) , 
7, 1.17801, 0, 0, 0.512301,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0354906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.1781, 0, 1, 0.719118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480659,-99) , 
2, 265.252, 0, 0, 0.562459,-99) , 
5, 187.086, 0, 0, 0.601472,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473757,-99) , 
1, 1.1781, 0, 0, 0.493459,-99) , 
NN(
0, 
0, 
-1, 1.17811, 1, -1, 0.401819,-99) , 
2, 285.37, 0, 0, 0.443988,-99) , 
3, -0.136511, 0, 0, 0.513692,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0382888);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.17805, 0, 1, 0.729794,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465525,-99) , 
2, 230.116, 0, 0, 0.575821,-99) , 
5, 193.059, 0, 0, 0.611216,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448819,-99) , 
2, 266.418, 0, 0, 0.511443,-99) , 
NN(
0, 
0, 
-1, 281.005, 0, -1, 0.413398,-99) , 
7, 0.981531, 0, 0, 0.453746,-99) , 
3, -0.13806, 0, 0, 0.523878,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0314224);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.087, 0, 1, 0.599235,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478793,-99) , 
5, 143.366, 0, 0, 0.498695,-99) , 
NN(
0, 
0, 
-1, 0.785406, 0, -1, 0.410467,-99) , 
7, 0.785228, 0, 0, 0.45662,-99) , 
3, -0.137255, 0, 0, 0.520329,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0313143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.089, 0, 1, 0.593504,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478885,-99) , 
1, 0.981723, 0, 0, 0.499285,-99) , 
NN(
0, 
0, 
-1, 200.203, 0, -1, 0.417009,-99) , 
2, 311.354, 0, 0, 0.449232,-99) , 
7, 1.37435, 0, 0, 0.514576,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0306703);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 164.506, 0, 1, 0.613564,-99) , 
NN(
NN(
0, 
0, 
-1, 212.555, 0, 1, 0.535389,-99) , 
NN(
0, 
0, 
-1, 232.582, 0, -1, 0.430216,-99) , 
2, 319.657, 0, 0, 0.471505,-99) , 
7, 1.76702, 0, 0, 0.520607,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0333031);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 282.064, 0, 1, 0.742648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469459,-99) , 
2, 248.399, 0, 0, 0.549589,-99) , 
5, 232.608, 0, 0, 0.569904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415696,-99) , 
2, 242.168, 0, 0, 0.487054,-99) , 
NN(
0, 
0, 
-1, 490.413, 0, -1, 0.404664,-99) , 
7, 0.980107, 0, 0, 0.433882,-99) , 
3, -0.247986, 0, 0, 0.517284,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0340007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 243.049, 0, 1, 0.697382,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447751,-99) , 
2, 247.88, 0, 0, 0.522942,-99) , 
5, 152.959, 0, 0, 0.577343,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433666,-99) , 
2, 287.068, 0, 0, 0.478169,-99) , 
NN(
0, 
0, 
-1, 0.957128, 0, -1, 0.399534,-99) , 
3, -0.296477, 0, 0, 0.43815,-99) , 
7, 1.17802, 0, 0, 0.510346,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0275487);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.059, 0, 1, 0.608692,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485744,-99) , 
5, 120.217, 0, 0, 0.520596,-99) , 
NN(
0, 
0, 
-1, 319.265, 0, -1, 0.440424,-99) , 
7, 0.981616, 0, 0, 0.478357,-99) , 
3, -0.0596674, 0, 0, 0.519325,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.03162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 226.404, 0, 1, 0.722359,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444548,-99) , 
2, 232.222, 0, 0, 0.527082,-99) , 
5, 172.715, 0, 0, 0.571587,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449607,-99) , 
5, 153.605, 0, 0, 0.468337,-99) , 
NN(
0, 
0, 
-1, 237.379, 0, -1, 0.390783,-99) , 
0, 0.98175, 0, 0, 0.444487,-99) , 
7, 1.17794, 0, 0, 0.51005,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0262662);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 222.064, 0, 1, 0.7158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443316,-99) , 
0, 2.15992, 0, 0, 0.507554,-99) , 
7, 1.17787, 0, 0, 0.639211,-99) , 
NN(
NN(
0, 
0, 
-1, 1.76691, 0, 1, 0.549284,-99) , 
NN(
0, 
0, 
-1, 72.9619, 0, -1, 0.457022,-99) , 
3, -0.104232, 0, 0, 0.487612,-99) , 
5, 172.46, 0, 0, 0.515382,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0296709);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 345.723, 0, 1, 0.735929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487823,-99) , 
5, 92.8384, 0, 0, 0.537488,-99) , 
5, 187.087, 0, 0, 0.57291,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47319,-99) , 
1, 1.17807, 0, 0, 0.495265,-99) , 
NN(
0, 
0, 
-1, 205.882, 0, -1, 0.41579,-99) , 
2, 298.349, 0, 0, 0.449905,-99) , 
7, 1.17794, 0, 0, 0.513357,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.025306);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 223.26, 0, 1, 0.704094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437199,-99) , 
0, 2.55254, 0, 0, 0.476149,-99) , 
7, 0.981583, 0, 0, 0.633652,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47625,-99) , 
6, 0.89956, 1, 0, 0.544617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430181,-99) , 
2, 272.684, 0, 0, 0.463706,-99) , 
7, 1.76711, 0, 0, 0.488456,-99) , 
5, 172.459, 0, 0, 0.51474,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.025614);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.06, 0, 1, 0.563006,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437161,-99) , 
5, 111.141, 0, 0, 0.474188,-99) , 
NN(
0, 
0, 
-1, 225.353, 0, -1, 0.400595,-99) , 
0, 0.981744, 0, 0, 0.447764,-99) , 
7, 0.981603, 0, 0, 0.515985,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0291167);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.064, 0, 1, 0.59083,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452464,-99) , 
5, 111.141, 0, 0, 0.494681,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386747,-99) , 
2, 237.379, 0, 0, 0.422061,-99) , 
0, 1.1781, 0, 0, 0.474204,-99) , 
7, 1.76701, 0, 0, 0.51472,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0236063);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.06, 0, 1, 0.577956,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474674,-99) , 
5, 196.793, 0, 0, 0.482423,-99) , 
NN(
0, 
0, 
-1, 2.85344, 1, -1, 0.396773,-99) , 
0, 0.785405, 0, 0, 0.467165,-99) , 
3, -0.137816, 0, 0, 0.516656,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0194677);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3742, 0, 1, 0.712232,-99) , 
NN(
NN(
0, 
0, 
-1, 153.174, 0, 1, 0.530692,-99) , 
NN(
0, 
0, 
-1, 0.78186, 0, -1, 0.456244,-99) , 
3, -0.23739, 0, 0, 0.498776,-99) , 
5, 233.42, 0, 0, 0.513606,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0209065);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 340.629, 0, 1, 0.730618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480118,-99) , 
7, 0.981455, 0, 0, 0.656415,-99) , 
NN(
NN(
0, 
0, 
-1, 139.413, 0, 1, 0.555716,-99) , 
NN(
0, 
0, 
-1, 245.266, 0, -1, 0.47259,-99) , 
7, 1.9632, 0, 0, 0.494638,-99) , 
5, 193.059, 0, 0, 0.515467,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0238767);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.981781, 0, 1, 0.644774,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472606,-99) , 
5, 92.8447, 0, 0, 0.515886,-99) , 
NN(
0, 
0, 
-1, 0.196366, 1, -1, 0.447394,-99) , 
7, 0.98153, 0, 0, 0.486723,-99) , 
5, 187.086, 0, 0, 0.509887,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0198106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 340.629, 0, 1, 0.719565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473525,-99) , 
7, 0.981779, 0, 0, 0.644393,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498746,-99) , 
5, 139.412, 0, 0, 0.520267,-99) , 
NN(
0, 
0, 
-1, 132.079, 0, -1, 0.452982,-99) , 
7, 0.981731, 0, 0, 0.491494,-99) , 
5, 193.059, 0, 0, 0.511322,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0217429);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729794,-99) , 
NN(
NN(
0, 
0, 
-1, 152.795, 0, 1, 0.565327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444272,-99) , 
2, 279.837, 0, 0, 0.476701,-99) , 
7, 1.76711, 0, 0, 0.506664,-99) , 
5, 255.628, 0, 0, 0.517926,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0182572);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.702286,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498682,-99) , 
5, 130.247, 0, 0, 0.526606,-99) , 
NN(
0, 
0, 
-1, 0.981748, 0, -1, 0.45878,-99) , 
7, 0.98173, 0, 0, 0.498074,-99) , 
5, 233.42, 0, 0, 0.512345,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0200532);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 255.656, 0, 1, 0.705798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48159,-99) , 
7, 0.785457, 0, 0, 0.647879,-99) , 
NN(
NN(
0, 
0, 
-1, 139.412, 0, 1, 0.541198,-99) , 
NN(
0, 
0, 
-1, 0.785397, 0, -1, 0.470292,-99) , 
7, 1.57038, 0, 0, 0.496615,-99) , 
5, 193.059, 0, 0, 0.516215,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0199263);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731795,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483563,-99) , 
5, 90.2267, 0, 0, 0.53169,-99) , 
NN(
0, 
0, 
-1, 0.981752, 0, -1, 0.460767,-99) , 
7, 0.981617, 0, 0, 0.502126,-99) , 
5, 264.588, 0, 0, 0.511961,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0160952);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.981644, 0, 1, 0.637641,-99) , 
NN(
NN(
0, 
0, 
-1, 121.529, 0, 1, 0.538628,-99) , 
NN(
0, 
0, 
-1, 2.74888, 1, -1, 0.481041,-99) , 
3, -0.105484, 0, 0, 0.500881,-99) , 
5, 193.059, 0, 0, 0.518499,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.017298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728701,-99) , 
NN(
NN(
0, 
0, 
-1, 152.806, 0, 1, 0.537508,-99) , 
NN(
0, 
0, 
-1, 1.17809, 0, -1, 0.470894,-99) , 
7, 1.17794, 0, 0, 0.504749,-99) , 
5, 255.629, 0, 0, 0.515942,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0164482);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736736,-99) , 
NN(
NN(
0, 
0, 
-1, 157.258, 0, 1, 0.534083,-99) , 
NN(
0, 
0, 
-1, 0.981748, 0, -1, 0.470584,-99) , 
7, 0.981627, 0, 0, 0.507328,-99) , 
5, 264.588, 0, 0, 0.517319,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0170648);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17804, 0, 1, 0.694421,-99) , 
NN(
NN(
0, 
0, 
-1, 164.634, 0, 1, 0.563004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465823,-99) , 
2, 289.446, 0, 0, 0.484958,-99) , 
3, -0.0387623, 0, 0, 0.504547,-99) , 
5, 233.42, 0, 0, 0.517656,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0193458);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 247.062, 0, 1, 0.679496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471758,-99) , 
7, 0.785292, 0, 0, 0.625629,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17806, 0, 1, 0.521717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427785,-99) , 
1, 1.37457, 1, 0, 0.467764,-99) , 
2, 248.838, 0, 0, 0.502255,-99) , 
5, 187.086, 0, 0, 0.519615,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0158064);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707851,-99) , 
NN(
NN(
0, 
0, 
-1, 170.709, 0, 1, 0.55205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468533,-99) , 
2, 279.837, 0, 0, 0.489666,-99) , 
7, 1.7669, 0, 0, 0.510762,-99) , 
5, 264.588, 0, 0, 0.518564,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0161506);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17804, 0, 1, 0.692006,-99) , 
NN(
NN(
0, 
0, 
-1, 176.283, 0, 1, 0.533809,-99) , 
NN(
0, 
0, 
-1, 248.384, 0, -1, 0.47393,-99) , 
3, -0.105205, 0, 0, 0.495674,-99) , 
5, 233.687, 0, 0, 0.509406,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0173493);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37443, 0, 1, 0.695533,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479965,-99) , 
7, 1.17799, 0, 0, 0.555407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480255,-99) , 
4, 311.227, 0, 0, 0.487064,-99) , 
5, 153.539, 0, 0, 0.500452,-99) , 
5, 234.071, 0, 0, 0.513526,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0149242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.981718, 0, 1, 0.624037,-99) , 
NN(
NN(
0, 
0, 
-1, 311.831, 0, 1, 0.519876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458595,-99) , 
3, -0.237634, 0, 0, 0.476059,-99) , 
7, 0.981604, 0, 0, 0.501317,-99) , 
5, 193.059, 0, 0, 0.517021,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0155721);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.6827,-99) , 
NN(
NN(
0, 
0, 
-1, 176.283, 0, 1, 0.56215,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47942,-99) , 
5, 141.841, 0, 0, 0.489123,-99) , 
3, 0.0152203, 0, 0, 0.50167,-99) , 
5, 233.687, 0, 0, 0.513819,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0139558);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.703726,-99) , 
NN(
NN(
0, 
0, 
-1, 1.37395, 0, 1, 0.553559,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484871,-99) , 
4, 332.871, 0, 0, 0.490427,-99) , 
5, 152.818, 0, 0, 0.504014,-99) , 
5, 255.632, 0, 0, 0.513684,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0182241);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 255.656, 0, 1, 0.684943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476741,-99) , 
7, 0.785377, 0, 0, 0.631208,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17809, 0, 1, 0.517246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425872,-99) , 
1, 1.37491, 1, 0, 0.471445,-99) , 
2, 265.161, 0, 0, 0.498823,-99) , 
5, 193.059, 0, 0, 0.516133,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0148146);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698292,-99) , 
NN(
NN(
0, 
0, 
-1, 178.49, 0, 1, 0.525872,-99) , 
NN(
0, 
0, 
-1, -0.421009, 0, -1, 0.467194,-99) , 
7, 0.981731, 0, 0, 0.501492,-99) , 
5, 255.628, 0, 0, 0.511029,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0177599);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.657249,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436,-99) , 
6, -1.19999, 0, 0, 0.51487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428407,-99) , 
2, 237.706, 0, 0, 0.451735,-99) , 
0, 1.17809, 0, 0, 0.502915,-99) , 
5, 234.07, 0, 0, 0.512566,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.01127);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705614,-99) , 
NN(
NN(
0, 
0, 
-1, 114.262, 0, 1, 0.559952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44094,-99) , 
6, -1.19999, 0, 0, 0.495213,-99) , 
3, 0.015628, 0, 0, 0.50673,-99) , 
5, 255.628, 0, 0, 0.516261,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0132939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.714894,-99) , 
NN(
NN(
0, 
0, 
-1, 170.704, 0, 1, 0.520519,-99) , 
NN(
0, 
0, 
-1, 2.94522, 1, -1, 0.464734,-99) , 
7, 0.785283, 0, 0, 0.502155,-99) , 
5, 264.588, 0, 0, 0.510924,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0181566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3742, 0, 1, 0.661301,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458285,-99) , 
6, 1.20003, 1, 0, 0.522044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450874,-99) , 
2, 406.987, 0, 0, 0.462884,-99) , 
3, -0.237634, 0, 0, 0.497197,-99) , 
5, 233.687, 0, 0, 0.507729,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0117536);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3742, 0, 1, 0.6598,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487614,-99) , 
6, -0.899226, 0, 0, 0.547405,-99) , 
NN(
0, 
0, 
-1, 0.785394, 0, -1, 0.48822,-99) , 
3, -0.0154742, 0, 0, 0.500951,-99) , 
5, 234.07, 0, 0, 0.511113,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0165867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 255.662, 0, 1, 0.670259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471392,-99) , 
7, 0.785454, 0, 0, 0.618874,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476325,-99) , 
2, 247.143, 0, 0, 0.535099,-99) , 
NN(
0, 
0, 
-1, 1.50001, 1, -1, 0.481001,-99) , 
5, 121.53, 0, 0, 0.498673,-99) , 
5, 193.059, 0, 0, 0.513933,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0114143);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706703,-99) , 
NN(
NN(
0, 
0, 
-1, 184.116, 0, 1, 0.545465,-99) , 
NN(
0, 
0, 
-1, 1.79943, 1, -1, 0.488119,-99) , 
3, -0.0393423, 0, 0, 0.503195,-99) , 
5, 264.589, 0, 0, 0.511724,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0143984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69798,-99) , 
NN(
NN(
0, 
0, 
-1, 157.292, 0, 1, 0.551671,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466155,-99) , 
2, 248.67, 0, 0, 0.494778,-99) , 
3, -0.0387623, 0, 0, 0.509835,-99) , 
5, 264.588, 0, 0, 0.517296,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00920944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685099,-99) , 
NN(
NN(
0, 
0, 
-1, 184.115, 0, 1, 0.549661,-99) , 
NN(
0, 
0, 
-1, 134.294, 0, -1, 0.491854,-99) , 
3, 0.000774458, 0, 0, 0.503399,-99) , 
5, 264.588, 0, 0, 0.510477,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0142626);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46596,-99) , 
2, 242.405, 0, 0, 0.538984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486178,-99) , 
4, 332.971, 0, 0, 0.490115,-99) , 
5, 130.47, 0, 0, 0.506126,-99) , 
5, 264.588, 0, 0, 0.514465,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0101403);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688566,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490666,-99) , 
7, 1.17807, 0, 0, 0.550885,-99) , 
NN(
0, 
0, 
-1, 1.50001, 1, -1, 0.494054,-99) , 
5, 152.806, 0, 0, 0.506196,-99) , 
5, 255.629, 0, 0, 0.514951,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0134201);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709363,-99) , 
NN(
NN(
0, 
0, 
-1, 170.701, 0, 1, 0.519647,-99) , 
NN(
0, 
0, 
-1, 0.981744, 0, -1, 0.462261,-99) , 
7, 0.785387, 0, 0, 0.500933,-99) , 
5, 264.588, 0, 0, 0.509951,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0100275);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690538,-99) , 
NN(
NN(
0, 
0, 
-1, 178.488, 0, 1, 0.536682,-99) , 
NN(
0, 
0, 
-1, 1.50024, 1, -1, 0.490816,-99) , 
7, 1.96296, 0, 0, 0.503652,-99) , 
5, 255.628, 0, 0, 0.512442,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00957364);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37426, 0, 1, 0.645333,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466589,-99) , 
7, 0.981583, 0, 0, 0.555141,-99) , 
NN(
0, 
0, 
-1, -1.20007, 0, -1, 0.491889,-99) , 
5, 176.102, 0, 0, 0.49882,-99) , 
5, 233.42, 0, 0, 0.50821,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0110787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.702093,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497313,-99) , 
5, 130.473, 0, 0, 0.512433,-99) , 
NN(
0, 
0, 
-1, 76.8186, 0, -1, 0.451602,-99) , 
6, 1.20003, 1, 0, 0.50469,-99) , 
5, 264.589, 0, 0, 0.512858,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0109313);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686827,-99) , 
NN(
NN(
0, 
0, 
-1, 157.291, 0, 1, 0.548382,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469611,-99) , 
3, -0.433903, 0, 0, 0.500079,-99) , 
3, 0.00214652, 0, 0, 0.509416,-99) , 
5, 264.588, 0, 0, 0.516482,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0152253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17789, 0, 1, 0.65919,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17799, 0, 1, 0.518184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446955,-99) , 
2, 219.841, 0, 0, 0.486069,-99) , 
2, 299.068, 0, 0, 0.502637,-99) , 
5, 233.687, 0, 0, 0.51298,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0139319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704771,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436878,-99) , 
6, 1.50013, 1, 0, 0.515719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471896,-99) , 
4, 311.227, 0, 0, 0.478642,-99) , 
5, 90.2355, 0, 0, 0.501149,-99) , 
5, 264.588, 0, 0, 0.509933,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00754925);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693689,-99) , 
NN(
NN(
0, 
0, 
-1, -1.60187e-05, 0, 1, 0.556519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443735,-99) , 
5, 58.3834, 0, 0, 0.494688,-99) , 
5, 184.115, 0, 0, 0.501556,-99) , 
5, 264.588, 0, 0, 0.509495,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.00845236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711202,-99) , 
NN(
NN(
0, 
0, 
-1, 1.5704, 0, 1, 0.578088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430728,-99) , 
6, 1.49994, 1, 0, 0.495632,-99) , 
5, 197.524, 0, 0, 0.502528,-99) , 
5, 264.588, 0, 0, 0.511643,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0100468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3742, 0, 1, 0.648137,-99) , 
NN(
NN(
0, 
0, 
-1, 176.546, 0, 1, 0.542402,-99) , 
NN(
0, 
0, 
-1, -1.19979, 0, -1, 0.488773,-99) , 
3, 0.015628, 0, 0, 0.498043,-99) , 
5, 234.07, 0, 0, 0.50772,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0112781);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.635752,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406332,-99) , 
2, 224.258, 0, 0, 0.538278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45055,-99) , 
6, -0.899772, 0, 0, 0.490159,-99) , 
5, 153.32, 0, 0, 0.499724,-99) , 
5, 233.687, 0, 0, 0.508443,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0126401);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37412, 0, 1, 0.640614,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479539,-99) , 
2, 248.838, 0, 0, 0.505703,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378365,-99) , 
0, 2.15983, 1, 0, 0.434563,-99) , 
6, 1.49942, 1, 0, 0.500362,-99) , 
5, 233.42, 0, 0, 0.509324,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0138001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698989,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456614,-99) , 
0, 0.981769, 0, 0, 0.520378,-99) , 
NN(
0, 
0, 
-1, 122.801, 0, -1, 0.480224,-99) , 
5, 90.2336, 0, 0, 0.504757,-99) , 
5, 264.588, 0, 0, 0.513027,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00719463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17741, 0, 1, 0.644718,-99) , 
NN(
NN(
0, 
0, 
-1, 187.56, 0, 1, 0.504818,-99) , 
NN(
0, 
0, 
-1, 1.78129, 1, -1, 0.439714,-99) , 
6, 1.5, 1, 0, 0.499955,-99) , 
5, 233.42, 0, 0, 0.50957,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00786539);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37443, 0, 1, 0.625351,-99) , 
NN(
NN(
0, 
0, 
-1, 432.116, 0, 1, 0.587457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472931,-99) , 
6, -0.899962, 0, 0, 0.496671,-99) , 
5, 211.78, 0, 0, 0.502388,-99) , 
4, 393.179, 0, 0, 0.510004,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0122718);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17811, 0, 1, 0.645901,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482079,-99) , 
7, 0.981746, 0, 0, 0.503129,-99) , 
NN(
0, 
0, 
-1, 141.809, 0, -1, 0.459795,-99) , 
6, 0.900055, 1, 0, 0.494386,-99) , 
5, 233.688, 0, 0, 0.504261,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00935229);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.1781, 0, 1, 0.65025,-99) , 
NN(
NN(
0, 
0, 
-1, 214.662, 0, 1, 0.57643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455735,-99) , 
6, -1.19946, 0, 0, 0.499551,-99) , 
5, 199.555, 0, 0, 0.503774,-99) , 
5, 234.07, 0, 0, 0.513464,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0142337);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37352, 0, 1, 0.660708,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465934,-99) , 
6, -1.16245, 0, 0, 0.512705,-99) , 
NN(
0, 
0, 
-1, 1.55629, 1, -1, 0.465636,-99) , 
6, 0.900039, 1, 0, 0.50319,-99) , 
5, 233.687, 0, 0, 0.513863,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0102828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651482,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468107,-99) , 
6, -1.19993, 0, 0, 0.509146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457582,-99) , 
3, -0.590689, 1, 0, 0.472456,-99) , 
4, 163.015, 0, 0, 0.501097,-99) , 
5, 255.629, 0, 0, 0.507894,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00981483);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678729,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461861,-99) , 
6, 1.20008, 1, 0, 0.503755,-99) , 
3, 0.118398, 0, 0, 0.50868,-99) , 
5, 264.588, 0, 0, 0.515596,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00762362);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660131,-99) , 
NN(
NN(
0, 
0, 
-1, 226.701, 0, 1, 0.557863,-99) , 
NN(
0, 
0, 
-1, 59.639, 0, -1, 0.490884,-99) , 
5, 204.208, 0, 0, 0.495094,-99) , 
5, 255.628, 0, 0, 0.502757,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00671075);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682675,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480081,-99) , 
7, 1.37353, 0, 0, 0.562427,-99) , 
NN(
0, 
0, 
-1, 1.79998, 1, -1, 0.496389,-99) , 
5, 197.51, 0, 0, 0.501609,-99) , 
5, 264.588, 0, 0, 0.509106,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00564467);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675921,-99) , 
NN(
NN(
0, 
0, 
-1, 224.346, 0, 1, 0.503234,-99) , 
NN(
0, 
0, 
-1, -0.000241041, 0, -1, 0.431734,-99) , 
4, 111.622, 0, 0, 0.498805,-99) , 
5, 264.588, 0, 0, 0.505993,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0105876);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699183,-99) , 
NN(
NN(
0, 
0, 
-1, 203.392, 0, 1, 0.515517,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460876,-99) , 
7, 0.147261, 1, 0, 0.470247,-99) , 
7, 0.785385, 0, 0, 0.500849,-99) , 
5, 295.426, 0, 0, 0.505957,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00952754);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67049,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491557,-99) , 
7, 1.17797, 0, 0, 0.568422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468565,-99) , 
6, 0.899953, 1, 0, 0.499937,-99) , 
5, 197.527, 0, 0, 0.505402,-99) , 
5, 264.588, 0, 0, 0.511978,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00829899);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712678,-99) , 
NN(
NN(
0, 
0, 
-1, 187.714, 0, 1, 0.541002,-99) , 
NN(
0, 
0, 
-1, 1.19997, 1, -1, 0.490382,-99) , 
3, 0.0149954, 0, 0, 0.499643,-99) , 
5, 294.916, 0, 0, 0.505446,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00768636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665362,-99) , 
NN(
NN(
0, 
0, 
-1, 231.048, 0, 1, 0.562815,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471009,-99) , 
6, 0.9, 1, 0, 0.498461,-99) , 
5, 210.931, 0, 0, 0.502009,-99) , 
5, 264.589, 0, 0, 0.508429,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.00915231);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666902,-99) , 
NN(
NN(
0, 
0, 
-1, 170.704, 0, 1, 0.534769,-99) , 
NN(
0, 
0, 
-1, -1.19993, 0, -1, 0.487763,-99) , 
3, 0.000774458, 0, 0, 0.497172,-99) , 
5, 264.588, 0, 0, 0.504087,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00804765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37414, 0, 1, 0.637337,-99) , 
NN(
NN(
0, 
0, 
-1, -0.017672, 0, 1, 0.529386,-99) , 
NN(
0, 
0, 
-1, 1.8, 1, -1, 0.492293,-99) , 
5, 153.538, 0, 0, 0.499556,-99) , 
5, 234.07, 0, 0, 0.508518,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00858133);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650126,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463706,-99) , 
6, -1.08745, 0, 0, 0.502114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422801,-99) , 
6, 1.79988, 1, 0, 0.498894,-99) , 
5, 264.59, 0, 0, 0.504591,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0114886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37437, 0, 1, 0.648535,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42871,-99) , 
6, 1.49977, 1, 0, 0.50495,-99) , 
NN(
0, 
0, 
-1, 111.705, 0, -1, 0.471412,-99) , 
7, 0.785191, 0, 0, 0.493907,-99) , 
5, 233.687, 0, 0, 0.504251,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0055349);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645623,-99) , 
NN(
NN(
0, 
0, 
-1, 217.071, 0, 1, 0.504068,-99) , 
NN(
0, 
0, 
-1, 83.9733, 0, -1, 0.438905,-99) , 
4, 111.622, 0, 0, 0.499975,-99) , 
5, 255.628, 0, 0, 0.506504,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_100_25_01_15::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_100_25_01_15::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
