// Class: ReadBDT_100_50_03_15
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_100_50_03_15
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Tue Sep 18 22:25:21 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 274422
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "15" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "3.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "3.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [5.96046447754e-06,3.14158797264]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [1.51991844177e-06,3.14158964157]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [86.8835525513,3932.9206543]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.99961078167,4.64822101593]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [0.213053271174,2188.19360352]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0001106262,1194.46325684]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39986610413,2.39999628067]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [9.05990600586e-06,3.14136242867]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_100_50_03_15Node
   
#ifndef BDT_100_50_03_15Node__def
#define BDT_100_50_03_15Node__def
   
class BDT_100_50_03_15Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_100_50_03_15Node ( BDT_100_50_03_15Node* left,BDT_100_50_03_15Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_100_50_03_15Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_100_50_03_15Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_100_50_03_15Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_100_50_03_15Node*   fLeft;     // pointer to the left daughter node
   BDT_100_50_03_15Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_100_50_03_15Node::~BDT_100_50_03_15Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_100_50_03_15Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_100_50_03_15Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_100_50_03_15 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_100_50_03_15( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_100_50_03_15" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_100_50_03_15() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_100_50_03_15Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_100_50_03_15::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_100_50_03_15Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_100_50_03_15Node*)current->GetRight();
         else current=(BDT_100_50_03_15Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_100_50_03_15::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.380683117222656);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 121.542, 0, 1, 0.710649,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384156,-99) , 
3, -0.117368, 0, 0, 0.443213,-99) , 
NN(
0, 
0, 
-1, 0.785403, 0, -1, 0.291559,-99) , 
2, 285.041, 0, 0, 0.360897,-99) , 
7, 1.57056, 0, 0, 0.500836,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.313934);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 121.515, 0, 1, 0.669043,-99) , 
NN(
0, 
0, 
-1, 280.129, 0, -1, 0.362547,-99) , 
7, 1.37435, 0, 0, 0.503742,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.306589);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 134.396, 0, 1, 0.660944,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417477,-99) , 
5, 171.736, 0, 0, 0.469308,-99) , 
NN(
0, 
0, 
-1, 201.14, 0, -1, 0.329975,-99) , 
2, 312.27, 0, 0, 0.385225,-99) , 
7, 1.57049, 0, 0, 0.496288,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.24134);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.775872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492077,-99) , 
3, -0.0966395, 0, 0, 0.55701,-99) , 
5, 166.894, 0, 0, 0.615066,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376092,-99) , 
3, -0.370519, 0, 0, 0.464151,-99) , 
NN(
0, 
0, 
-1, 0.981696, 0, -1, 0.327104,-99) , 
2, 288.94, 0, 0, 0.388623,-99) , 
7, 1.17802, 0, 0, 0.506571,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.254407);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.83, 0, 1, 0.655452,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442961,-99) , 
7, 0.993739, 0, 0, 0.503674,-99) , 
NN(
0, 
0, 
-1, 0.993952, 0, -1, 0.37082,-99) , 
2, 319.657, 0, 0, 0.422843,-99) , 
7, 1.76703, 0, 0, 0.504685,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.225865);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 187.086, 0, 1, 0.616677,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437315,-99) , 
5, 108.977, 0, 0, 0.489055,-99) , 
NN(
0, 
0, 
-1, 256.712, 0, -1, 0.363009,-99) , 
7, 0.979472, 0, 0, 0.418104,-99) , 
3, -0.114558, 0, 0, 0.500528,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.193745);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.773417,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451245,-99) , 
3, -0.203829, 0, 0, 0.538149,-99) , 
5, 187.094, 0, 0, 0.582561,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44615,-99) , 
5, 111.141, 0, 0, 0.481071,-99) , 
NN(
0, 
0, 
-1, 226.055, 0, -1, 0.376959,-99) , 
2, 309.467, 0, 0, 0.418829,-99) , 
7, 1.17789, 0, 0, 0.503124,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.163867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 166.905, 0, 1, 0.611287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483581,-99) , 
5, 165.9, 0, 0, 0.518878,-99) , 
NN(
0, 
0, 
-1, 0.589019, 0, -1, 0.419591,-99) , 
2, 319.657, 0, 0, 0.458849,-99) , 
7, 1.76702, 0, 0, 0.510713,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.159893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 193.06, 0, 1, 0.612898,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424192,-99) , 
2, 222.692, 0, 0, 0.504635,-99) , 
NN(
0, 
0, 
-1, 280.555, 0, -1, 0.415182,-99) , 
7, 0.785177, 0, 0, 0.466741,-99) , 
3, -0.06653, 0, 0, 0.514268,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.143047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.743976,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450907,-99) , 
2, 242.444, 0, 0, 0.5281,-99) , 
5, 199.347, 0, 0, 0.561255,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43892,-99) , 
4, 245.279, 0, 0, 0.459853,-99) , 
NN(
0, 
0, 
-1, 222.649, 1, -1, 0.401308,-99) , 
0, 0.981773, 0, 0, 0.441621,-99) , 
7, 1.17803, 0, 0, 0.503126,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.120047);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17817, 0, 1, 0.662233,-99) , 
NN(
NN(
0, 
0, 
-1, 1.96233, 0, 1, 0.551306,-99) , 
NN(
0, 
0, 
-1, 247.182, 0, -1, 0.459279,-99) , 
3, -0.0666936, 0, 0, 0.485119,-99) , 
5, 193.003, 0, 0, 0.50909,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.144457);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457219,-99) , 
7, 0.981649, 0, 0, 0.627003,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440927,-99) , 
2, 227.535, 0, 0, 0.535981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444734,-99) , 
3, 0.00146562, 0, 0, 0.45446,-99) , 
5, 118.771, 0, 0, 0.478975,-99) , 
5, 172.28, 0, 0, 0.506311,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.10694);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37429, 0, 1, 0.649616,-99) , 
NN(
NN(
0, 
0, 
-1, 121.53, 0, 1, 0.534586,-99) , 
NN(
0, 
0, 
-1, 0.785429, 0, -1, 0.459976,-99) , 
7, 1.9629, 0, 0, 0.479609,-99) , 
5, 193.059, 0, 0, 0.502079,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0932335);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740348,-99) , 
NN(
NN(
0, 
0, 
-1, 139.946, 0, 1, 0.525065,-99) , 
NN(
0, 
0, 
-1, 191.007, 0, -1, 0.40103,-99) , 
0, 0.981748, 0, 0, 0.506511,-99) , 
5, 255.629, 0, 0, 0.518375,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0962948);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37433, 0, 1, 0.628251,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423432,-99) , 
6, -1.0501, 0, 0, 0.501346,-99) , 
NN(
0, 
0, 
-1, 0.589158, 0, -1, 0.415728,-99) , 
6, 1.19951, 1, 0, 0.490038,-99) , 
5, 193.058, 0, 0, 0.508271,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0992277);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671115,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17809, 0, 1, 0.521545,-99) , 
NN(
0, 
0, 
-1, 1.37458, 1, -1, 0.424854,-99) , 
2, 248.223, 0, 0, 0.48935,-99) , 
5, 225.34, 0, 0, 0.503231,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0960996);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37439, 0, 1, 0.615332,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474006,-99) , 
5, 112.571, 0, 0, 0.49712,-99) , 
NN(
0, 
0, 
-1, 0.779632, 0, -1, 0.434796,-99) , 
3, -0.313761, 0, 0, 0.476351,-99) , 
5, 193.002, 0, 0, 0.49429,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0778112);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37369, 0, 1, 0.615046,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565163,-99) , 
NN(
0, 
0, 
-1, 202.035, 0, -1, 0.479184,-99) , 
4, 312.299, 0, 0, 0.488404,-99) , 
5, 187.086, 0, 0, 0.507167,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0893667);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670048,-99) , 
NN(
NN(
0, 
0, 
-1, 152.711, 0, 1, 0.527987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455729,-99) , 
2, 492.914, 0, 0, 0.464864,-99) , 
7, 1.17779, 0, 0, 0.496735,-99) , 
5, 232.605, 0, 0, 0.508572,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0696741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665788,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47882,-99) , 
1, 0.196351, 1, 0, 0.487111,-99) , 
3, 0.0521982, 0, 0, 0.495116,-99) , 
5, 233.42, 0, 0, 0.506581,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0728895);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473832,-99) , 
7, 1.37421, 0, 0, 0.589938,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464771,-99) , 
6, 0.824641, 1, 0, 0.501194,-99) , 
NN(
0, 
0, 
-1, 0.589109, 1, -1, 0.431587,-99) , 
6, -1.19993, 0, 0, 0.492582,-99) , 
5, 193.058, 0, 0, 0.504931,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0688349);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650228,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494514,-99) , 
7, 1.17788, 0, 0, 0.550522,-99) , 
NN(
0, 
0, 
-1, 263.125, 0, -1, 0.483439,-99) , 
5, 142.031, 0, 0, 0.500168,-99) , 
5, 234.069, 0, 0, 0.51009,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.065991);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651985,-99) , 
NN(
NN(
0, 
0, 
-1, 126.712, 0, 1, 0.542201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466962,-99) , 
2, 237.017, 0, 0, 0.49033,-99) , 
7, 1.96312, 0, 0, 0.504655,-99) , 
5, 225.34, 0, 0, 0.515846,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0434827);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646788,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578143,-99) , 
NN(
0, 
0, 
-1, -0.900247, 0, -1, 0.491154,-99) , 
4, 334.602, 0, 0, 0.498599,-99) , 
4, 411.479, 0, 0, 0.506401,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0665769);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649147,-99) , 
NN(
NN(
0, 
0, 
-1, 142.039, 0, 1, 0.538885,-99) , 
NN(
0, 
0, 
-1, -0.900104, 0, -1, 0.480718,-99) , 
7, 1.96312, 0, 0, 0.496926,-99) , 
5, 234.07, 0, 0, 0.50732,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0733894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17796, 0, 1, 0.591678,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434502,-99) , 
6, -1.19993, 0, 0, 0.513285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46431,-99) , 
7, 0.368078, 1, 0, 0.476756,-99) , 
7, 0.981531, 0, 0, 0.497683,-99) , 
5, 187.089, 0, 0, 0.511024,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0603345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649195,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497038,-99) , 
5, 130.357, 0, 0, 0.515131,-99) , 
NN(
0, 
0, 
-1, 107.4, 1, -1, 0.473571,-99) , 
7, 0.78531, 0, 0, 0.501515,-99) , 
5, 233.686, 0, 0, 0.511499,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0946721);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446664,-99) , 
6, -1.19994, 0, 0, 0.518156,-99) , 
5, 187.094, 0, 0, 0.535844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465841,-99) , 
1, 0.736292, 0, 0, 0.483085,-99) , 
NN(
0, 
0, 
-1, 0.441593, 0, -1, 0.42387,-99) , 
1, 2.3562, 1, 0, 0.464409,-99) , 
7, 0.785252, 0, 0, 0.512834,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0541806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606328,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482399,-99) , 
6, -0.900211, 0, 0, 0.513073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454812,-99) , 
1, 0.785464, 0, 0, 0.478242,-99) , 
5, 73.0079, 0, 0, 0.50463,-99) , 
5, 234.069, 0, 0, 0.510962,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0538113);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465857,-99) , 
7, 1.37439, 0, 0, 0.561221,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471265,-99) , 
6, -0.693878, 0, 0, 0.498691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442773,-99) , 
6, 1.49977, 1, 0, 0.494323,-99) , 
4, 333.151, 0, 0, 0.502921,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0432524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602626,-99) , 
NN(
0, 
0, 
-1, 0.899595, 1, -1, 0.489773,-99) , 
5, 215.88, 0, 0, 0.49665,-99) , 
4, 410.459, 0, 0, 0.503402,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0607057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475467,-99) , 
7, 0.981618, 0, 0, 0.516516,-99) , 
3, 0.0359552, 0, 0, 0.553115,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496808,-99) , 
7, 0.785304, 1, 0, 0.50838,-99) , 
NN(
0, 
0, 
-1, 2.74887, 1, -1, 0.47962,-99) , 
3, -0.236383, 0, 0, 0.493489,-99) , 
4, 275.13, 0, 0, 0.509769,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.076974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474815,-99) , 
7, 1.37436, 0, 0, 0.568701,-99) , 
NN(
NN(
0, 
0, 
-1, 309.158, 0, 1, 0.5355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465399,-99) , 
5, 139.412, 0, 0, 0.47533,-99) , 
1, 0.785395, 0, 0, 0.500972,-99) , 
5, 193.059, 0, 0, 0.50912,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0658791);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.37421, 0, 1, 0.5851,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482074,-99) , 
0, 1.76736, 0, 0, 0.518765,-99) , 
NN(
0, 
0, 
-1, -0.347274, 0, -1, 0.474638,-99) , 
3, -0.197726, 0, 0, 0.497291,-99) , 
5, 193.058, 0, 0, 0.508564,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0612873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467482,-99) , 
6, 1.20004, 1, 0, 0.511958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450273,-99) , 
0, 0.785417, 0, 0, 0.504913,-99) , 
4, 358.296, 0, 0, 0.513284,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0456807);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.392648, 1, 1, 0.581858,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460185,-99) , 
6, 1.19968, 1, 0, 0.500209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452758,-99) , 
5, 58.9388, 0, 0, 0.495517,-99) , 
5, 193.003, 0, 0, 0.50657,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0415468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.17797, 0, 1, 0.577695,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45808,-99) , 
0, 0.785434, 0, 0, 0.497275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422781,-99) , 
6, -1.49982, 0, 0, 0.492132,-99) , 
5, 193.059, 0, 0, 0.503369,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.048539);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592155,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441787,-99) , 
6, -1.36867, 0, 0, 0.502147,-99) , 
NN(
0, 
0, 
-1, 84.24, 1, -1, 0.461974,-99) , 
6, 0.899535, 1, 0, 0.494102,-99) , 
5, 232.604, 0, 0, 0.500344,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0363683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497868,-99) , 
3, -0.596487, 1, 0, 0.502568,-99) , 
NN(
0, 
0, 
-1, 84.3824, 0, -1, 0.468159,-99) , 
6, -0.899979, 0, 0, 0.495762,-99) , 
5, 233.42, 0, 0, 0.503488,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0431103);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595562,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479521,-99) , 
7, 0.981626, 0, 0, 0.496691,-99) , 
NN(
0, 
0, 
-1, 0.589148, 0, -1, 0.46725,-99) , 
6, 0.899951, 1, 0, 0.490668,-99) , 
4, 411.531, 0, 0, 0.496006,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0425406);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56977,-99) , 
NN(
0, 
0, 
-1, 242.897, 0, -1, 0.486732,-99) , 
5, 215.88, 0, 0, 0.491769,-99) , 
4, 411.531, 0, 0, 0.497615,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0640622);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620683,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496579,-99) , 
1, 1.17811, 0, 0, 0.508748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434407,-99) , 
1, 1.3746, 1, 0, 0.471226,-99) , 
2, 238.168, 0, 0, 0.497062,-99) , 
4, 410.459, 0, 0, 0.503835,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0648908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.74911, 1, 1, 0.560322,-99) , 
NN(
NN(
0, 
0, 
-1, 1.17804, 0, 1, 0.521913,-99) , 
NN(
0, 
0, 
-1, 2.74912, 0, -1, 0.448383,-99) , 
2, 192.372, 0, 0, 0.507538,-99) , 
2, 508.882, 0, 0, 0.515114,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0436547);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.74974, 1, 1, 0.550053,-99) , 
NN(
NN(
0, 
0, 
-1, 1.57079, 0, 1, 0.513481,-99) , 
NN(
0, 
0, 
-1, 224.389, 1, -1, 0.465445,-99) , 
2, 198.244, 0, 0, 0.503283,-99) , 
2, 531.892, 0, 0, 0.508905,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0526106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586607,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471826,-99) , 
2, 236.307, 0, 0, 0.497314,-99) , 
5, 193.059, 0, 0, 0.509351,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463887,-99) , 
6, -0.074973, 1, 0, 0.479358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421314,-99) , 
6, -0.899775, 0, 0, 0.469117,-99) , 
7, 0.785297, 0, 0, 0.496395,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0326397);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468814,-99) , 
4, 246.756, 1, 0, 0.492458,-99) , 
3, 0.0884656, 0, 0, 0.496594,-99) , 
4, 393.713, 0, 0, 0.50142,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.056729);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586807,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488183,-99) , 
2, 291.413, 0, 0, 0.512741,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480144,-99) , 
2, 291.3, 1, 0, 0.48973,-99) , 
1, 0.785394, 0, 0, 0.498814,-99) , 
5, 233.42, 0, 0, 0.504514,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0304321);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570911,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496602,-99) , 
2, 567.638, 0, 0, 0.500719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442257,-99) , 
6, 1.50006, 1, 0, 0.496342,-99) , 
3, 0.134643, 0, 0, 0.50189,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0585399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470589,-99) , 
7, 1.37446, 0, 0, 0.546089,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494043,-99) , 
2, 297.771, 0, 0, 0.512941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476985,-99) , 
2, 280.77, 1, 0, 0.488003,-99) , 
1, 0.785412, 0, 0, 0.498031,-99) , 
5, 193.003, 0, 0, 0.504013,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0386985);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552195,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450571,-99) , 
3, -0.487036, 0, 0, 0.5032,-99) , 
3, -0.575427, 1, 0, 0.507763,-99) , 
3, 0.131575, 0, 0, 0.51418,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0396385);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610176,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494072,-99) , 
1, 0.78544, 0, 0, 0.504073,-99) , 
NN(
0, 
0, 
-1, 206.363, 1, -1, 0.461392,-99) , 
6, 1.19999, 1, 0, 0.498497,-99) , 
4, 411.201, 0, 0, 0.504383,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0410814);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 393.378, 0, 1, 0.517257,-99) , 
NN(
0, 
0, 
-1, 1.96333, 0, -1, 0.453974,-99) , 
4, 136.962, 0, 0, 0.510059,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0343398);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468531,-99) , 
6, 1.49981, 1, 0, 0.504141,-99) , 
NN(
0, 
0, 
-1, -1.64981, 0, -1, 0.466945,-99) , 
6, -1.19983, 0, 0, 0.499507,-99) , 
5, 232.604, 0, 0, 0.504957,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0452124);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477124,-99) , 
1, 0.981735, 0, 0, 0.488233,-99) , 
5, 211.779, 0, 0, 0.491645,-99) , 
4, 393.437, 0, 0, 0.495695,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0538176);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488668,-99) , 
0, 1.96403, 1, 0, 0.503651,-99) , 
5, 187.086, 0, 0, 0.511128,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458292,-99) , 
4, 222.912, 1, 0, 0.488268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4344,-99) , 
0, 0.589088, 0, 0, 0.470476,-99) , 
7, 0.588695, 0, 0, 0.501782,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0305989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495304,-99) , 
3, -0.536323, 1, 0, 0.500541,-99) , 
3, 0.0593577, 0, 0, 0.50553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449515,-99) , 
6, -1.49959, 0, 0, 0.501624,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0355619);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.00142121, 1, 1, 0.541327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492537,-99) , 
1, 0.981716, 0, 0, 0.499833,-99) , 
5, 193.059, 0, 0, 0.505046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443688,-99) , 
0, 0.589094, 0, 0, 0.500341,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0634903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630271,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494346,-99) , 
3, 0.00706497, 0, 0, 0.507753,-99) , 
1, 0.785325, 0, 0, 0.522668,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448794,-99) , 
3, -0.430439, 0, 0, 0.498611,-99) , 
NN(
0, 
0, 
-1, 154.643, 1, -1, 0.446487,-99) , 
2, 207.222, 0, 0, 0.47826,-99) , 
2, 327.41, 0, 0, 0.498826,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0560555);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575905,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496231,-99) , 
5, 135.675, 0, 0, 0.505182,-99) , 
5, 187.086, 0, 0, 0.515757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46938,-99) , 
4, 133.66, 0, 0, 0.515292,-99) , 
NN(
0, 
0, 
-1, 0.981833, 0, -1, 0.451508,-99) , 
5, 108.223, 1, 0, 0.489009,-99) , 
7, 0.981682, 0, 0, 0.504675,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0309073);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49801,-99) , 
1, 2.55251, 0, 0, 0.50632,-99) , 
NN(
0, 
0, 
-1, 1.37443, 0, -1, 0.482517,-99) , 
6, -0.599892, 0, 0, 0.499574,-99) , 
5, 216.742, 0, 0, 0.504179,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0691898);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497327,-99) , 
0, 2.78297, 0, 0, 0.517963,-99) , 
3, -0.366261, 1, 0, 0.525252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484128,-99) , 
1, 1.25174, 0, 0, 0.514954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458439,-99) , 
4, 147, 1, 0, 0.4738,-99) , 
2, 238.86, 0, 0, 0.497431,-99) , 
1, 0.392717, 1, 0, 0.507323,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0569837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498915,-99) , 
1, 0.0981715, 1, 0, 0.51143,-99) , 
1, 0.785382, 0, 0, 0.527896,-99) , 
NN(
NN(
0, 
0, 
-1, 253.484, 0, 1, 0.514061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433787,-99) , 
2, 155.044, 1, 0, 0.455605,-99) , 
2, 207.63, 0, 0, 0.491792,-99) , 
2, 327.801, 0, 0, 0.50841,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.052915);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499047,-99) , 
3, 0.0203797, 0, 0, 0.513392,-99) , 
1, 0.785335, 0, 0, 0.527993,-99) , 
NN(
NN(
0, 
0, 
-1, 1.5708, 1, 1, 0.514388,-99) , 
NN(
0, 
0, 
-1, 215.983, 1, -1, 0.453681,-99) , 
2, 188.485, 0, 0, 0.496356,-99) , 
2, 319.116, 0, 0, 0.511485,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0545668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.785345, 0, 1, 0.523638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47476,-99) , 
1, 0.982354, 1, 0, 0.49531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432198,-99) , 
6, -0.900026, 0, 0, 0.484602,-99) , 
2, 289.331, 0, 0, 0.50685,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0493924);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.74896, 1, 1, 0.547324,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461237,-99) , 
2, 190.575, 0, 0, 0.504964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450646,-99) , 
4, 135.505, 0, 0, 0.477192,-99) , 
4, 166.323, 0, 0, 0.498095,-99) , 
2, 493.172, 0, 0, 0.505647,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0592654);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616772,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494931,-99) , 
5, 210.487, 0, 0, 0.505597,-99) , 
1, 0.785316, 0, 0, 0.519805,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484806,-99) , 
4, 263.365, 0, 0, 0.495249,-99) , 
NN(
0, 
0, 
-1, 0.490821, 1, -1, 0.433092,-99) , 
0, 0.981654, 0, 0, 0.480156,-99) , 
2, 319.265, 0, 0, 0.499455,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0521557);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.65677, 1, 1, 0.526994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471783,-99) , 
1, 2.82605, 0, 0, 0.498196,-99) , 
0, 0.981786, 0, 0, 0.522582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471755,-99) , 
2, 360.707, 0, 0, 0.485696,-99) , 
6, -1.19995, 0, 0, 0.51821,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.027342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529666,-99) , 
NN(
0, 
0, 
-1, 73.014, 0, -1, 0.491809,-99) , 
1, 2.74888, 0, 0, 0.495632,-99) , 
5, 234.074, 0, 0, 0.499904,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0335633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562744,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468569,-99) , 
4, 110.032, 0, 0, 0.526429,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455695,-99) , 
5, 188.023, 1, 0, 0.49625,-99) , 
3, -0.39554, 1, 0, 0.503439,-99) , 
5, 234.069, 0, 0, 0.507221,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0525463);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46407,-99) , 
2, 220.053, 0, 0, 0.504374,-99) , 
2, 579.367, 0, 0, 0.510893,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479692,-99) , 
6, 0.899422, 0, 0, 0.488787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408115,-99) , 
5, 172.281, 1, 0, 0.477449,-99) , 
7, 0.981685, 0, 0, 0.497397,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.063227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41606,-99) , 
3, -0.145957, 1, 0, 0.49214,-99) , 
2, 222.746, 0, 0, 0.526942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479099,-99) , 
2, 283.929, 1, 0, 0.487854,-99) , 
5, 232.604, 0, 0, 0.492738,-99) , 
1, 0.981745, 0, 0, 0.503495,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0384105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562658,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451906,-99) , 
6, 1.49956, 1, 0, 0.506934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46339,-99) , 
1, 2.74889, 1, 0, 0.502948,-99) , 
4, 386.557, 0, 0, 0.507036,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0346207);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547777,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492496,-99) , 
1, 1.96345, 0, 0, 0.501162,-99) , 
NN(
0, 
0, 
-1, 107.402, 0, -1, 0.47984,-99) , 
4, 234.592, 1, 0, 0.492692,-99) , 
5, 233.686, 0, 0, 0.496273,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0320226);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546841,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497037,-99) , 
2, 378.345, 0, 0, 0.504063,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447308,-99) , 
7, 1.57052, 0, 0, 0.47589,-99) , 
0, 2.74887, 1, 0, 0.49568,-99) , 
5, 234.07, 0, 0, 0.498926,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.05103);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598769,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478199,-99) , 
6, -0.900192, 0, 0, 0.503567,-99) , 
1, 0.78537, 0, 0, 0.516041,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480336,-99) , 
4, 208.388, 1, 0, 0.502704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447979,-99) , 
2, 203.756, 0, 0, 0.4674,-99) , 
1, 1.96352, 1, 0, 0.490139,-99) , 
2, 320.495, 0, 0, 0.502488,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0292794);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496558,-99) , 
5, 121.531, 0, 0, 0.505738,-99) , 
3, -0.533087, 1, 0, 0.509343,-99) , 
NN(
0, 
0, 
-1, 0.441836, 1, -1, 0.470596,-99) , 
0, 0.785446, 0, 0, 0.504981,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0514239);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.00438225, 0, 1, 0.5419,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488106,-99) , 
4, 353.721, 0, 0, 0.495357,-99) , 
0, 1.5729, 1, 0, 0.503632,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466055,-99) , 
3, -0.310855, 0, 0, 0.491108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430916,-99) , 
5, 166.444, 1, 0, 0.481324,-99) , 
7, 0.785295, 0, 0, 0.496514,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0360806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498521,-99) , 
0, 2.16112, 1, 0, 0.509573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461697,-99) , 
1, 1.37456, 1, 0, 0.488363,-99) , 
2, 309.318, 0, 0, 0.499246,-99) , 
7, 0.196329, 1, 0, 0.502316,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0385798);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486784,-99) , 
0, 1.76715, 1, 0, 0.497401,-99) , 
7, 2.35574, 0, 0, 0.502446,-99) , 
2, 670.456, 0, 0, 0.505295,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0485269);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48058,-99) , 
6, 0.299753, 1, 0, 0.505026,-99) , 
1, 0.785383, 0, 0, 0.51496,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48111,-99) , 
3, -0.247248, 0, 0, 0.505892,-99) , 
NN(
0, 
0, 
-1, 0.148959, 0, -1, 0.480972,-99) , 
6, -0.600487, 1, 0, 0.488111,-99) , 
2, 320.346, 0, 0, 0.500956,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.034756);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548912,-99) , 
NN(
NN(
0, 
0, 
-1, 328.863, 0, 1, 0.51106,-99) , 
NN(
0, 
0, 
-1, 110.869, 1, -1, 0.480128,-99) , 
7, 1.11667, 0, 0, 0.498235,-99) , 
7, 0.196344, 1, 0, 0.502173,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0400177);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.35629, 1, 1, 0.519367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475722,-99) , 
1, 1.17844, 1, 0, 0.493799,-99) , 
2, 322.757, 0, 0, 0.505629,-99) , 
NN(
0, 
0, 
-1, 1.37296, 0, -1, 0.459501,-99) , 
6, -1.19987, 0, 0, 0.500072,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0645675);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.000284553, 1, 1, 0.588476,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439619,-99) , 
1, 2.65083, 0, 0, 0.488471,-99) , 
2, 205.391, 0, 0, 0.528099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555049,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483371,-99) , 
2, 281.206, 1, 0, 0.492766,-99) , 
5, 234.07, 0, 0, 0.497314,-99) , 
1, 1.17808, 0, 0, 0.505813,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0465663);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545898,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488528,-99) , 
5, 193.003, 0, 0, 0.49723,-99) , 
3, -0.406766, 1, 0, 0.503939,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47893,-99) , 
3, -0.196164, 0, 0, 0.4895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434113,-99) , 
5, 166.444, 1, 0, 0.480463,-99) , 
7, 0.785294, 0, 0, 0.496435,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0540306);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475579,-99) , 
1, 0.49074, 1, 0, 0.5138,-99) , 
1, 0.785336, 0, 0, 0.523394,-99) , 
NN(
NN(
0, 
0, 
-1, 0.785356, 1, 1, 0.513894,-99) , 
NN(
0, 
0, 
-1, -0.301636, 1, -1, 0.474303,-99) , 
0, 2.15966, 0, 0, 0.490498,-99) , 
2, 311.969, 0, 0, 0.507093,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0349697);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499557,-99) , 
2, 277.719, 0, 0, 0.515362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481829,-99) , 
0, 2.88394, 0, 0, 0.499203,-99) , 
0, 2.55255, 1, 0, 0.508363,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464965,-99) , 
5, 92.4392, 1, 0, 0.482928,-99) , 
6, -1.20004, 0, 0, 0.505279,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0493438);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483091,-99) , 
0, 0.785449, 0, 0, 0.522071,-99) , 
NN(
0, 
0, 
-1, -1.34537, 0, -1, 0.486128,-99) , 
6, -0.712663, 0, 0, 0.509299,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465711,-99) , 
6, 1.1619, 1, 0, 0.505999,-99) , 
NN(
0, 
0, 
-1, 1.27457, 0, -1, 0.470715,-99) , 
0, 2.15987, 1, 0, 0.484606,-99) , 
6, 0.599644, 1, 0, 0.502117,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.062426);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455383,-99) , 
1, 2.71215, 0, 0, 0.491354,-99) , 
2, 223.618, 0, 0, 0.529229,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485619,-99) , 
7, 0.785363, 0, 0, 0.513713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47672,-99) , 
6, -0.599707, 1, 0, 0.490936,-99) , 
5, 118.543, 0, 0, 0.501266,-99) , 
1, 1.76713, 0, 0, 0.50789,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0370309);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 235.113, 0, 1, 0.53063,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497321,-99) , 
5, 172.716, 0, 0, 0.504357,-99) , 
1, 0.981737, 0, 0, 0.512765,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476922,-99) , 
5, 150.985, 1, 0, 0.508104,-99) , 
NN(
0, 
0, 
-1, 95.8498, 1, -1, 0.469934,-99) , 
2, 291.447, 0, 0, 0.492004,-99) , 
6, -0.600036, 0, 0, 0.506859,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0576282);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485694,-99) , 
1, 2.35591, 1, 0, 0.529879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452564,-99) , 
0, 1.96333, 0, 0, 0.476032,-99) , 
3, -0.509969, 0, 0, 0.514055,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471184,-99) , 
2, 277.596, 0, 0, 0.506059,-99) , 
NN(
0, 
0, 
-1, 1.57071, 0, -1, 0.481205,-99) , 
0, 2.55258, 1, 0, 0.493345,-99) , 
4, 197.153, 1, 0, 0.50104,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0441258);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49837,-99) , 
1, 1.52171, 0, 0, 0.54111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473366,-99) , 
1, 2.40535, 1, 0, 0.494118,-99) , 
2, 219.093, 0, 0, 0.514882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519158,-99) , 
NN(
0, 
0, 
-1, -0.111128, 1, -1, 0.484428,-99) , 
3, 0.0152007, 0, 0, 0.492429,-99) , 
1, 0.785395, 0, 0, 0.501171,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0348694);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524418,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48506,-99) , 
7, 0.783467, 0, 0, 0.498506,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431038,-99) , 
7, 1.96337, 0, 0, 0.471152,-99) , 
3, -0.0687919, 1, 0, 0.49234,-99) , 
3, 0.0634856, 0, 0, 0.49652,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0345667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48608,-99) , 
7, 0.552733, 0, 0, 0.52735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466968,-99) , 
7, 1.37406, 0, 0, 0.517422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453462,-99) , 
5, 172.281, 1, 0, 0.49522,-99) , 
3, -0.0220689, 0, 0, 0.501401,-99) , 
1, 2.55253, 0, 0, 0.504944,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0357959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 97.9284, 0, 1, 0.527304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473743,-99) , 
1, 2.74872, 0, 0, 0.492194,-99) , 
0, 1.96349, 0, 0, 0.512087,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494971,-99) , 
0, 2.35689, 1, 0, 0.500418,-99) , 
NN(
0, 
0, 
-1, 195.632, 0, -1, 0.481928,-99) , 
2, 330.718, 0, 0, 0.492414,-99) , 
4, 197.506, 1, 0, 0.499806,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0434657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.76715, 0, 1, 0.529668,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469774,-99) , 
2, 323.528, 1, 0, 0.492815,-99) , 
3, -0.0285653, 0, 0, 0.507061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507386,-99) , 
NN(
0, 
0, 
-1, 1.21451, 1, -1, 0.480427,-99) , 
7, 2.15927, 0, 0, 0.484831,-99) , 
5, 121.531, 0, 0, 0.494,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0225196);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.57028, 1, 1, 0.536603,-99) , 
NN(
NN(
0, 
0, 
-1, 0.196323, 1, 1, 0.506365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475508,-99) , 
1, 2.74885, 1, 0, 0.503321,-99) , 
2, 553.947, 0, 0, 0.506954,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.031496);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473363,-99) , 
6, 1.50006, 1, 0, 0.508247,-99) , 
NN(
0, 
0, 
-1, 2.55258, 0, -1, 0.476284,-99) , 
6, -1.19975, 0, 0, 0.504516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444343,-99) , 
1, 0.981876, 1, 0, 0.477213,-99) , 
4, 138.198, 0, 0, 0.501136,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0407264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 111.243, 1, 1, 0.547662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496839,-99) , 
4, 164.79, 0, 0, 0.529107,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492886,-99) , 
1, 0.674724, 0, 0, 0.49986,-99) , 
NN(
0, 
0, 
-1, 2.16524, 0, -1, 0.475269,-99) , 
2, 321.11, 0, 0, 0.489186,-99) , 
1, 2.15985, 0, 0, 0.497176,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0425357);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.586842, 0, 1, 0.539821,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469468,-99) , 
2, 206.935, 1, 0, 0.50546,-99) , 
2, 278.97, 0, 0, 0.52062,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492574,-99) , 
4, 232.745, 1, 0, 0.502295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458097,-99) , 
7, 0.392715, 0, 0, 0.498426,-99) , 
3, -0.290053, 1, 0, 0.506005,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0480836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492364,-99) , 
1, 0.392681, 1, 0, 0.505177,-99) , 
2, 669.835, 0, 0, 0.509482,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472759,-99) , 
1, 1.37499, 1, 0, 0.501025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459358,-99) , 
2, 254.319, 1, 0, 0.491325,-99) , 
2, 292.094, 0, 0, 0.501389,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_100_50_03_15::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_100_50_03_15::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
