// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Wed Sep 12 16:34:58 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 463792
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "1.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
tmva_n_btags                  tmva_n_btags                  tmva_n_btags                  N of b-tags                                                     'I'    [1,6]
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [2.32458114624e-06,3.14159083366]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [1.51991844177e-06,3.14159035683]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [86.5497436523,5391.02001953]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.99961078167,4.05550050735]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [0.213053271174,1788.81921387]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0001945496,1194.01318359]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39999055862,2.39996170998]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [2.32458114624e-06,3.14152240753]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_n_btags", "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.0822832886603706);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 137.24, 0, 1, 0.738435,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.702112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460999,-99) , 
4, -0.0763287, 0, 0, 0.514504,-99) , 
NN(
0, 
0, 
-1, 208.318, 0, -1, 0.27106,-99) , 
3, 269.202, 0, 0, 0.365086,-99) , 
8, 1.49586, 0, 0, 0.502109,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.0791639);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 224.75, 0, 1, 0.727796,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453171,-99) , 
5, 274.103, 0, 0, 0.510694,-99) , 
NN(
0, 
0, 
-1, 206.13, 0, -1, 0.275704,-99) , 
3, 265.089, 0, 0, 0.369841,-99) , 
8, 1.49597, 0, 0, 0.499498,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.0802106);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 128.264, 0, 1, 0.729784,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424937,-99) , 
4, -0.150717, 0, 0, 0.491708,-99) , 
NN(
0, 
0, 
-1, 1.79523, 1, -1, 0.275933,-99) , 
3, 247.569, 0, 0, 0.370561,-99) , 
8, 1.49589, 0, 0, 0.503402,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0713928);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.964, 0, 1, 0.712177,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46348,-99) , 
6, 179.623, 0, 0, 0.504375,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.294372,-99) , 
3, 261.566, 0, 0, 0.379759,-99) , 
8, 1.49596, 0, 0, 0.500431,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0743437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 149.529, 0, 1, 0.741353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409615,-99) , 
3, 220.721, 0, 0, 0.690887,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438806,-99) , 
5, 220.959, 0, 0, 0.507754,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.298795,-99) , 
3, 263.505, 0, 0, 0.382723,-99) , 
8, 1.34637, 0, 0, 0.50839,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0700522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.956, 0, 1, 0.71882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465712,-99) , 
5, 255.728, 0, 0, 0.532825,-99) , 
NN(
0, 
0, 
-1, 199.62, 0, -1, 0.309575,-99) , 
3, 269.202, 0, 0, 0.400127,-99) , 
8, 1.64548, 0, 0, 0.503121,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0664089);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 137.251, 0, 1, 0.713626,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485022,-99) , 
8, 1.01862, 0, 0, 0.546329,-99) , 
NN(
0, 
0, 
-1, 209.927, 0, -1, 0.318375,-99) , 
3, 270.786, 0, 0, 0.410684,-99) , 
8, 1.64548, 0, 0, 0.507974,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0598919);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 167.401, 0, 1, 0.703985,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49624,-99) , 
4, -0.0457718, 0, 0, 0.534697,-99) , 
NN(
0, 
0, 
-1, 1.94483, 1, -1, 0.318676,-99) , 
3, 249.153, 0, 0, 0.416105,-99) , 
8, 1.64537, 0, 0, 0.508038,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0642128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 182.519, 0, 1, 0.798278,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432923,-99) , 
3, 248.245, 0, 0, 0.584627,-99) , 
6, 141.243, 0, 0, 0.670165,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473999,-99) , 
6, 143.166, 0, 0, 0.525596,-99) , 
NN(
0, 
0, 
-1, 1.94482, 1, -1, 0.32482,-99) , 
3, 264.372, 0, 0, 0.406766,-99) , 
8, 1.3463, 0, 0, 0.513678,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0614537);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 194.549, 0, 1, 0.801006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470587,-99) , 
3, 253.636, 0, 0, 0.597132,-99) , 
6, 149.522, 0, 0, 0.668256,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457819,-99) , 
4, -0.281375, 0, 0, 0.523118,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.330447,-99) , 
3, 265.828, 0, 0, 0.407709,-99) , 
8, 1.34637, 0, 0, 0.514274,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0623953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 194.546, 0, 1, 0.794616,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38802,-99) , 
3, 222.034, 0, 0, 0.584035,-99) , 
6, 149.522, 0, 0, 0.658457,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464258,-99) , 
6, 143.904, 0, 0, 0.512604,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.333965,-99) , 
3, 269.202, 0, 0, 0.404114,-99) , 
8, 1.34637, 0, 0, 0.507187,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.060639);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 199.29, 0, 1, 0.751541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476855,-99) , 
8, 0.897181, 0, 0, 0.559386,-99) , 
4, -0.0323717, 0, 0, 0.62764,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451313,-99) , 
4, -0.199227, 0, 0, 0.54359,-99) , 
NN(
0, 
0, 
-1, 226.092, 0, -1, 0.317322,-99) , 
2, 1.34645, 1, 0, 0.389611,-99) , 
3, 269.71, 0, 0, 0.514316,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0523784);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 194.565, 0, 1, 0.788273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493786,-99) , 
4, -0.199917, 0, 0, 0.60359,-99) , 
6, 149.533, 0, 0, 0.671127,-99) , 
NN(
NN(
0, 
0, 
-1, 190.855, 0, 1, 0.544823,-99) , 
NN(
0, 
0, 
-1, 1.9448, 1, -1, 0.358087,-99) , 
3, 270.498, 0, 0, 0.433009,-99) , 
8, 1.49589, 0, 0, 0.518025,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0561545);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 199.283, 0, 1, 0.72892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473395,-99) , 
8, 0.896975, 0, 0, 0.542628,-99) , 
4, -0.047769, 0, 0, 0.610252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420231,-99) , 
4, -0.331472, 0, 0, 0.516732,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.31599,-99) , 
2, 1.64567, 1, 0, 0.372568,-99) , 
3, 241.541, 0, 0, 0.515589,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0504827);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0442363, 0, 1, 0.614029,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426,-99) , 
4, -0.251996, 0, 0, 0.496421,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.330498,-99) , 
2, 1.79523, 1, 0, 0.383572,-99) , 
3, 248.436, 0, 0, 0.517333,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0460962);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.956, 0, 1, 0.677812,-99) , 
NN(
NN(
0, 
0, 
-1, 236.332, 0, 1, 0.544325,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.377204,-99) , 
3, 263.505, 0, 0, 0.450326,-99) , 
8, 1.79485, 0, 0, 0.513417,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0489821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 176.706, 0, 1, 0.75441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404967,-99) , 
3, 214.177, 0, 0, 0.553183,-99) , 
6, 137.24, 0, 0, 0.634566,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478015,-99) , 
4, -0.102778, 0, 0, 0.508511,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.36336,-99) , 
3, 248.864, 0, 0, 0.428603,-99) , 
8, 1.34637, 0, 0, 0.511768,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0453333);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 385.3, 0, 1, 0.785603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453032,-99) , 
1, 1.3464, 0, 0, 0.615816,-99) , 
6, 199.283, 0, 0, 0.656806,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490259,-99) , 
6, 143.167, 0, 0, 0.525542,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.367831,-99) , 
3, 247.569, 0, 0, 0.44649,-99) , 
4, -0.0738667, 0, 0, 0.512622,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0426323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.966, 0, 1, 0.670203,-99) , 
NN(
NN(
0, 
0, 
-1, 237.807, 0, 1, 0.548522,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.397719,-99) , 
3, 270.069, 0, 0, 0.460612,-99) , 
8, 1.79504, 0, 0, 0.518923,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0455138);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 319.238, 0, 1, 0.779283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43535,-99) , 
3, 220.312, 0, 0, 0.559751,-99) , 
6, 167.668, 0, 0, 0.615535,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466617,-99) , 
6, 138.305, 0, 0, 0.488451,-99) , 
NN(
0, 
0, 
-1, 205.321, 0, -1, 0.350969,-99) , 
1, 1.0472, 0, 0, 0.424973,-99) , 
8, 1.19677, 0, 0, 0.512513,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0396318);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 213.432, 0, 1, 0.644311,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490284,-99) , 
6, 130.353, 0, 0, 0.522465,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.383805,-99) , 
3, 249.567, 0, 0, 0.452311,-99) , 
4, -0.0763287, 0, 0, 0.512763,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0407273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.529, 0, 1, 0.627182,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475011,-99) , 
2, 0.897597, 0, 0, 0.516021,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.394235,-99) , 
3, 263.505, 0, 0, 0.44488,-99) , 
8, 1.3463, 0, 0, 0.517683,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0377506);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430192,-99) , 
3, 210.174, 0, 0, 0.616223,-99) , 
6, 199.285, 0, 0, 0.663535,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495324,-99) , 
6, 142.752, 0, 0, 0.528681,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.409633,-99) , 
3, 264.8, 0, 0, 0.465169,-99) , 
4, -0.0330939, 0, 0, 0.514457,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0366796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 141.243, 0, 1, 0.607441,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479082,-99) , 
6, 189.749, 0, 0, 0.49342,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.369322,-99) , 
1, 1.0472, 0, 0, 0.43628,-99) , 
8, 1.19677, 0, 0, 0.514283,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0379254);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 167.675, 0, 1, 0.651032,-99) , 
NN(
NN(
0, 
0, 
-1, 237.806, 0, 1, 0.542801,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.406034,-99) , 
3, 264.372, 0, 0, 0.465832,-99) , 
8, 1.79485, 0, 0, 0.517352,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.038647);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 208.254, 0, 1, 0.741474,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442425,-99) , 
3, 220.549, 0, 0, 0.550578,-99) , 
6, 158.961, 0, 0, 0.603707,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471382,-99) , 
6, 143.166, 0, 0, 0.491769,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.385271,-99) , 
1, 1.04719, 0, 0, 0.442414,-99) , 
8, 1.19677, 0, 0, 0.515657,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0336527);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 213.432, 0, 1, 0.648936,-99) , 
NN(
NN(
0, 
0, 
-1, 189.127, 0, 1, 0.535233,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.411803,-99) , 
3, 248.864, 0, 0, 0.475113,-99) , 
4, -0.0367324, 0, 0, 0.519241,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0322658);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 199.286, 0, 1, 0.632145,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481869,-99) , 
6, 143.167, 0, 0, 0.506203,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.405782,-99) , 
1, 1.1968, 0, 0, 0.468238,-99) , 
4, -0.0704469, 0, 0, 0.517934,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0359679);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.783867,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441423,-99) , 
3, 217.668, 0, 0, 0.56111,-99) , 
6, 186.874, 0, 0, 0.604618,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468131,-99) , 
4, -0.24573, 0, 0, 0.502974,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.394592,-99) , 
1, 1.0472, 0, 0, 0.456977,-99) , 
8, 1.34614, 0, 0, 0.516456,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0334271);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 199.281, 0, 1, 0.619948,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491867,-99) , 
2, 1.34639, 0, 0, 0.518506,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.403208,-99) , 
3, 241.534, 0, 0, 0.462883,-99) , 
4, -0.102804, 0, 0, 0.518484,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0337904);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.34591, 0, 1, 0.738579,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457206,-99) , 
3, 229.767, 0, 0, 0.574865,-99) , 
6, 190.855, 0, 0, 0.616372,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471192,-99) , 
6, 89.8766, 0, 0, 0.505787,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.395964,-99) , 
1, 1.0472, 0, 0, 0.468076,-99) , 
4, -0.103885, 0, 0, 0.52089,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.03225);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.19671, 0, 1, 0.674163,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493799,-99) , 
4, -0.072796, 0, 0, 0.517261,-99) , 
6, 158.954, 0, 0, 0.556396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613093,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.377926,-99) , 
3, 322.197, 0, 0, 0.403046,-99) , 
1, 1.1968, 0, 0, 0.511523,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0329922);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 149.53, 0, 1, 0.627232,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483185,-99) , 
2, 1.0472, 0, 0, 0.530425,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.428376,-99) , 
3, 269.202, 0, 0, 0.471686,-99) , 
8, 1.79507, 0, 0, 0.514697,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0282815);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 199.282, 0, 1, 0.592632,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480509,-99) , 
4, -0.280997, 0, 0, 0.50212,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.402297,-99) , 
1, 0.897599, 0, 0, 0.463021,-99) , 
8, 1.19663, 0, 0, 0.521866,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0264359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 213.432, 0, 1, 0.610812,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499672,-99) , 
6, 210.706, 0, 0, 0.509471,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.407269,-99) , 
3, 219.502, 0, 0, 0.46722,-99) , 
4, -0.0794385, 0, 0, 0.513511,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0257559);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 186.864, 0, 1, 0.619459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497851,-99) , 
6, 226.609, 0, 0, 0.510761,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.392189,-99) , 
1, 0.897598, 0, 0, 0.475532,-99) , 
8, 1.79507, 0, 0, 0.515905,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0252026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.956, 0, 1, 0.612931,-99) , 
NN(
NN(
0, 
0, 
-1, 367.777, 0, 1, 0.51866,-99) , 
NN(
0, 
0, 
-1, 205.321, 0, -1, 0.424986,-99) , 
1, 1.04721, 0, 0, 0.483686,-99) , 
8, 1.64537, 0, 0, 0.524235,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0277877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.790938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498821,-99) , 
8, 1.34634, 0, 0, 0.586874,-99) , 
6, 237.808, 0, 0, 0.617216,-99) , 
NN(
NN(
0, 
0, 
-1, 1.04719, 0, 1, 0.530457,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359179,-99) , 
0, 2, 1, 0, 0.444718,-99) , 
3, 249.334, 0, 0, 0.488506,-99) , 
4, -0.0331998, 0, 0, 0.519629,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0294946);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44195,-99) , 
3, 210.174, 0, 0, 0.580964,-99) , 
6, 232.628, 0, 0, 0.61717,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497773,-99) , 
2, 0.897599, 0, 0, 0.522523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341016,-99) , 
0, 2, 1, 0, 0.432302,-99) , 
3, 240.4, 0, 0, 0.480973,-99) , 
4, -0.0442363, 0, 0, 0.516875,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0234791);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.743262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498853,-99) , 
8, 1.04714, 0, 0, 0.653967,-99) , 
NN(
NN(
0, 
0, 
-1, 0.8976, 0, 1, 0.527704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375776,-99) , 
0, 2, 1, 0, 0.446839,-99) , 
3, 241.892, 0, 0, 0.492368,-99) , 
6, 190.855, 0, 0, 0.513443,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0285741);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 208.248, 0, 1, 0.712369,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49379,-99) , 
6, 96.691, 0, 0, 0.531094,-99) , 
6, 158.957, 0, 0, 0.580297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476247,-99) , 
2, 0.897595, 0, 0, 0.510329,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.428242,-99) , 
3, 259.982, 0, 0, 0.463727,-99) , 
8, 1.19671, 0, 0, 0.51657,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0258033);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.770358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443405,-99) , 
3, 201.485, 0, 0, 0.574201,-99) , 
6, 213.435, 0, 0, 0.614252,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495542,-99) , 
6, 143.166, 0, 0, 0.513201,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.413412,-99) , 
1, 1.0472, 0, 0, 0.48126,-99) , 
4, -0.0449732, 0, 0, 0.516487,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0261961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.755219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494755,-99) , 
8, 0.896933, 0, 0, 0.670401,-99) , 
NN(
NN(
0, 
0, 
-1, 1.0472, 0, 1, 0.542421,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381961,-99) , 
0, 2, 1, 0, 0.452312,-99) , 
3, 249.153, 0, 0, 0.501897,-99) , 
6, 199.28, 0, 0, 0.521187,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0260184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.766842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488536,-99) , 
8, 0.897553, 0, 0, 0.677535,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491325,-99) , 
8, 1.04718, 0, 0, 0.53326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367448,-99) , 
0, 2, 1, 0, 0.446212,-99) , 
3, 239.057, 0, 0, 0.497133,-99) , 
6, 213.432, 0, 0, 0.513392,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0239927);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.3463, 0, 1, 0.718835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491509,-99) , 
4, -0.132059, 0, 0, 0.521927,-99) , 
6, 213.431, 0, 0, 0.54151,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441926,-99) , 
3, 194.339, 0, 0, 0.468899,-99) , 
NN(
0, 
0, 
-1, -0.308972, 0, -1, 0.363038,-99) , 
0, 2, 1, 0, 0.408599,-99) , 
1, 0.897598, 0, 0, 0.512786,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0245129);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.897178, 0, 1, 0.689847,-99) , 
NN(
NN(
0, 
0, 
-1, -0.0339367, 0, 1, 0.538838,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379668,-99) , 
0, 2, 1, 0, 0.444542,-99) , 
3, 239.057, 0, 0, 0.499398,-99) , 
6, 213.432, 0, 0, 0.517121,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0191069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19665, 0, 1, 0.680869,-99) , 
NN(
NN(
0, 
0, 
-1, 135.606, 0, 1, 0.521883,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.432208,-99) , 
1, 1.04719, 0, 0, 0.497797,-99) , 
6, 213.431, 0, 0, 0.514535,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0212377);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19561, 0, 1, 0.671585,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490585,-99) , 
6, 104.477, 0, 0, 0.520709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398023,-99) , 
3, 204.371, 0, 0, 0.436795,-99) , 
1, 1.19683, 0, 0, 0.495344,-99) , 
6, 213.431, 0, 0, 0.511099,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0285278);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 274.046, 0, 1, 0.714874,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471891,-99) , 
5, 170.949, 0, 0, 0.537802,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.420463,-99) , 
3, 216.255, 0, 0, 0.498273,-99) , 
6, 236.331, 0, 0, 0.512454,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0198724);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 275.815, 0, 1, 0.71086,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495681,-99) , 
6, 112.6, 0, 0, 0.525381,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.437447,-99) , 
1, 1.04718, 0, 0, 0.502227,-99) , 
6, 237.806, 0, 0, 0.515216,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.018796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 199.281, 0, 1, 0.595081,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496254,-99) , 
6, 189.127, 0, 0, 0.505472,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.428344,-99) , 
1, 1.0472, 0, 0, 0.481171,-99) , 
4, -0.0347353, 0, 0, 0.509352,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0178273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 274.053, 0, 1, 0.698231,-99) , 
NN(
NN(
0, 
0, 
-1, 138.728, 0, 1, 0.52333,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.428155,-99) , 
1, 0.897602, 0, 0, 0.502196,-99) , 
6, 236.332, 0, 0, 0.514556,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0185661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480627,-99) , 
8, 0.897569, 0, 0, 0.650901,-99) , 
NN(
NN(
0, 
0, 
-1, 357.042, 0, 1, 0.51573,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.433566,-99) , 
1, 1.19681, 0, 0, 0.49105,-99) , 
6, 199.281, 0, 0, 0.509528,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0232688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.753793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498021,-99) , 
8, 0.897537, 0, 0, 0.67013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449762,-99) , 
3, 213.306, 0, 0, 0.526906,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.46099,-99) , 
8, 0.897579, 0, 0, 0.498496,-99) , 
6, 213.431, 0, 0, 0.514169,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0147248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4825,-99) , 
8, 0.897493, 0, 0, 0.650069,-99) , 
NN(
NN(
0, 
0, 
-1, 357.042, 0, 1, 0.507039,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.434013,-99) , 
1, 0.897608, 0, 0, 0.490416,-99) , 
6, 199.281, 0, 0, 0.508878,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0203615);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19615, 0, 1, 0.651163,-99) , 
NN(
NN(
0, 
0, 
-1, 0.897608, 0, 1, 0.520591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381026,-99) , 
0, 2, 1, 0, 0.44902,-99) , 
3, 233.6, 0, 0, 0.491657,-99) , 
6, 199.281, 0, 0, 0.509907,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0170115);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 275.819, 0, 1, 0.697931,-99) , 
NN(
NN(
0, 
0, 
-1, 314.396, 0, 1, 0.593198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457925,-99) , 
3, 249.153, 0, 0, 0.485727,-99) , 
4, 0.0653364, 0, 0, 0.497165,-99) , 
6, 237.807, 0, 0, 0.509739,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0158015);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477388,-99) , 
8, 0.897477, 0, 0, 0.642596,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497313,-99) , 
5, 341.968, 0, 0, 0.504489,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.423448,-99) , 
1, 0.897598, 0, 0, 0.486257,-99) , 
6, 199.281, 0, 0, 0.503736,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.01384);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739705,-99) , 
NN(
NN(
0, 
0, 
-1, 164.141, 0, 1, 0.561697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448106,-99) , 
1, 0.897599, 0, 0, 0.485516,-99) , 
8, 1.94462, 0, 0, 0.502777,-99) , 
6, 267.908, 0, 0, 0.512286,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0205386);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 275.819, 0, 1, 0.690245,-99) , 
NN(
NN(
0, 
0, 
-1, 1.1968, 0, 1, 0.524605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424944,-99) , 
3, 203.165, 0, 0, 0.465283,-99) , 
3, 249.153, 0, 0, 0.498817,-99) , 
6, 237.807, 0, 0, 0.510328,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0170322);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709733,-99) , 
NN(
NN(
0, 
0, 
-1, 106.877, 0, 1, 0.561891,-99) , 
NN(
0, 
0, 
-1, 261.566, 0, -1, 0.475072,-99) , 
8, 1.94442, 0, 0, 0.49484,-99) , 
6, 249.04, 0, 0, 0.505967,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.016039);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 274.058, 0, 1, 0.685967,-99) , 
NN(
NN(
0, 
0, 
-1, 1.64548, 0, 1, 0.562138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446186,-99) , 
1, 1.1968, 0, 0, 0.483533,-99) , 
4, -0.0342705, 0, 0, 0.501111,-99) , 
6, 236.331, 0, 0, 0.512597,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0110396);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.04714, 0, 1, 0.66051,-99) , 
NN(
NN(
0, 
0, 
-1, 354.381, 0, 1, 0.506272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410301,-99) , 
0, 2, 1, 0, 0.449797,-99) , 
1, 0.747997, 0, 0, 0.495995,-99) , 
6, 213.431, 0, 0, 0.510653,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0177933);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715513,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431663,-99) , 
3, 206.94, 0, 0, 0.536598,-99) , 
NN(
0, 
0, 
-1, 0.747997, 0, -1, 0.480623,-99) , 
6, 125.823, 0, 0, 0.499132,-99) , 
6, 249.041, 0, 0, 0.510476,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0123272);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.897553, 0, 1, 0.663123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615809,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451886,-99) , 
1, 1.0472, 0, 0, 0.488888,-99) , 
4, 0.156809, 0, 0, 0.495164,-99) , 
6, 224.564, 0, 0, 0.507783,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0151856);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.897553, 0, 1, 0.656925,-99) , 
NN(
NN(
0, 
0, 
-1, 127.829, 0, 1, 0.540139,-99) , 
NN(
0, 
0, 
-1, 119.683, 0, -1, 0.478167,-99) , 
8, 1.94421, 0, 0, 0.491695,-99) , 
6, 213.431, 0, 0, 0.506898,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0128537);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 453.694, 0, 1, 0.686353,-99) , 
NN(
NN(
0, 
0, 
-1, 300.125, 0, 1, 0.573548,-99) , 
NN(
0, 
0, 
-1, 0.897605, 0, -1, 0.485908,-99) , 
4, 0.0458038, 0, 0, 0.496886,-99) , 
6, 235.501, 0, 0, 0.509015,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0141015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.04715, 0, 1, 0.652445,-99) , 
NN(
NN(
0, 
0, 
-1, 133.092, 0, 1, 0.545927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466996,-99) , 
3, 247.569, 0, 0, 0.483787,-99) , 
8, 1.79485, 0, 0, 0.499854,-99) , 
6, 224.477, 0, 0, 0.51096,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0214282);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19671, 0, 1, 0.630652,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485581,-99) , 
2, 1.04715, 0, 0, 0.51137,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39576,-99) , 
0, 2, 1, 0, 0.459368,-99) , 
3, 226.934, 0, 0, 0.491524,-99) , 
6, 199.281, 0, 0, 0.506912,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0116043);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.1966, 0, 1, 0.632503,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494376,-99) , 
4, 0.0219531, 0, 0, 0.502373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390879,-99) , 
5, 86.2666, 0, 0, 0.497859,-99) , 
6, 199.282, 0, 0, 0.512948,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0186146);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4841,-99) , 
8, 0.897203, 0, 0, 0.641921,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491448,-99) , 
2, 1.0472, 0, 0, 0.514763,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40714,-99) , 
0, 2, 1, 0, 0.45893,-99) , 
3, 239.057, 0, 0, 0.492003,-99) , 
6, 213.431, 0, 0, 0.505372,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0144418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19663, 0, 1, 0.647536,-99) , 
NN(
NN(
0, 
0, 
-1, 380.209, 0, 1, 0.516446,-99) , 
NN(
0, 
0, 
-1, 207.459, 0, -1, 0.46319,-99) , 
4, -0.274845, 0, 0, 0.493973,-99) , 
6, 213.432, 0, 0, 0.507766,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0134807);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.708916,-99) , 
NN(
NN(
0, 
0, 
-1, 164.141, 0, 1, 0.519181,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.451343,-99) , 
1, 1.0472, 0, 0, 0.501787,-99) , 
6, 267.908, 0, 0, 0.509645,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0142961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464835,-99) , 
8, 1.04716, 0, 0, 0.651449,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495816,-99) , 
6, 125.686, 0, 0, 0.516383,-99) , 
NN(
0, 
0, 
-1, 0.748013, 0, -1, 0.468762,-99) , 
4, -0.303409, 0, 0, 0.498354,-99) , 
6, 226.609, 0, 0, 0.509105,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0132571);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 443.157, 0, 1, 0.672744,-99) , 
NN(
NN(
0, 
0, 
-1, 1.94408, 0, 1, 0.567143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462914,-99) , 
1, 1.34639, 0, 0, 0.489722,-99) , 
4, 0.0215286, 0, 0, 0.501237,-99) , 
6, 237.806, 0, 0, 0.511468,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0169661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19674, 0, 1, 0.629417,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495782,-99) , 
2, 1.04719, 0, 0, 0.516293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417466,-99) , 
0, 2, 1, 0, 0.464626,-99) , 
3, 239.057, 0, 0, 0.494778,-99) , 
6, 199.28, 0, 0, 0.50992,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0171664);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 273.069, 0, 1, 0.672451,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481774,-99) , 
8, 1.04711, 0, 0, 0.520279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46867,-99) , 
3, 509.127, 0, 0, 0.473294,-99) , 
6, 103.001, 0, 0, 0.495885,-99) , 
6, 235.502, 0, 0, 0.506887,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0143722);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474887,-99) , 
8, 0.897509, 0, 0, 0.633525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460562,-99) , 
3, 216.544, 0, 0, 0.493475,-99) , 
4, 0.156809, 0, 0, 0.49844,-99) , 
6, 213.432, 0, 0, 0.510287,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0138267);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493449,-99) , 
8, 1.04714, 0, 0, 0.632785,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488164,-99) , 
6, 120.042, 0, 0, 0.502947,-99) , 
NN(
0, 
0, 
-1, -0.324543, 0, -1, 0.446849,-99) , 
1, 0.748002, 0, 0, 0.492931,-99) , 
6, 213.431, 0, 0, 0.505304,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0109473);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 455.492, 0, 1, 0.664132,-99) , 
NN(
NN(
0, 
0, 
-1, 164.826, 0, 1, 0.545562,-99) , 
NN(
0, 
0, 
-1, 111.684, 0, -1, 0.489664,-99) , 
4, -0.0367324, 0, 0, 0.502185,-99) , 
6, 235.502, 0, 0, 0.512302,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.012013);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678721,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475821,-99) , 
8, 0.897522, 0, 0, 0.496566,-99) , 
4, 0.154492, 0, 0, 0.501773,-99) , 
6, 249.04, 0, 0, 0.510715,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0125332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599552,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466919,-99) , 
3, 241.534, 0, 0, 0.491901,-99) , 
4, 0.156809, 0, 0, 0.497436,-99) , 
6, 267.907, 0, 0, 0.505719,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.013597);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711556,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0257648, 0, 1, 0.547177,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480375,-99) , 
3, 433.414, 0, 0, 0.486838,-99) , 
8, 1.94476, 0, 0, 0.500585,-99) , 
6, 267.907, 0, 0, 0.5088,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0109639);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 274.046, 0, 1, 0.652413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605917,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4599,-99) , 
1, 0.897599, 0, 0, 0.496335,-99) , 
4, 0.154492, 0, 0, 0.501993,-99) , 
6, 236.331, 0, 0, 0.511069,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0113126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 275.815, 0, 1, 0.660765,-99) , 
NN(
NN(
0, 
0, 
-1, 0.141915, 0, 1, 0.517814,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.476773,-99) , 
4, -0.287783, 0, 0, 0.501543,-99) , 
6, 237.806, 0, 0, 0.510918,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00972074);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 275.815, 0, 1, 0.658268,-99) , 
NN(
NN(
0, 
0, 
-1, 1.94422, 0, 1, 0.551673,-99) , 
NN(
0, 
0, 
-1, 1.25713, 1, -1, 0.489362,-99) , 
4, 0.0436314, 0, 0, 0.497175,-99) , 
6, 237.806, 0, 0, 0.506785,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0108209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663019,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497449,-99) , 
8, 1.34595, 0, 0, 0.530877,-99) , 
NN(
0, 
0, 
-1, 86.2535, 0, -1, 0.486766,-99) , 
6, 125.822, 0, 0, 0.501324,-99) , 
6, 249.04, 0, 0, 0.509317,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0082963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 269.418, 0, 1, 0.649022,-99) , 
NN(
NN(
0, 
0, 
-1, 0.156371, 0, 1, 0.508214,-99) , 
NN(
0, 
0, 
-1, 110.813, 0, -1, 0.439524,-99) , 
7, -1.48539, 0, 0, 0.503195,-99) , 
6, 232.483, 0, 0, 0.512452,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00942955);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.19671, 0, 1, 0.624057,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498255,-99) , 
4, 0.0588853, 0, 0, 0.504413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41048,-99) , 
5, 85.3786, 0, 0, 0.500535,-99) , 
6, 199.281, 0, 0, 0.51433,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00800488);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692848,-99) , 
NN(
NN(
0, 
0, 
-1, 366.059, 0, 1, 0.565565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454544,-99) , 
5, 131.287, 0, 0, 0.494525,-99) , 
4, 0.0653364, 0, 0, 0.502191,-99) , 
6, 270.76, 0, 0, 0.508988,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00908342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664603,-99) , 
NN(
NN(
0, 
0, 
-1, 345.224, 0, 1, 0.54375,-99) , 
NN(
0, 
0, 
-1, -1.02858, 0, -1, 0.489065,-99) , 
4, 0.0436314, 0, 0, 0.496042,-99) , 
6, 249.04, 0, 0, 0.50458,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.00851071);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 453.694, 0, 1, 0.649603,-99) , 
NN(
NN(
0, 
0, 
-1, 410.552, 0, 1, 0.509617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394378,-99) , 
5, 86.2535, 0, 0, 0.505192,-99) , 
6, 237.806, 0, 0, 0.513626,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0113322);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668137,-99) , 
NN(
NN(
0, 
0, 
-1, 182.693, 0, 1, 0.516311,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.472204,-99) , 
4, -0.273946, 0, 0, 0.498253,-99) , 
6, 249.041, 0, 0, 0.506668,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00903159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 273.056, 0, 1, 0.655818,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580685,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463855,-99) , 
7, -1.02858, 0, 0, 0.498507,-99) , 
4, 0.157123, 0, 0, 0.502382,-99) , 
6, 235.501, 0, 0, 0.511922,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0169674);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691129,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452306,-99) , 
3, 204.077, 0, 0, 0.513416,-99) , 
NN(
0, 
0, 
-1, 0.427312, 1, -1, 0.463275,-99) , 
8, 0.747799, 0, 0, 0.496215,-99) , 
6, 267.907, 0, 0, 0.503667,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0127005);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 457.912, 0, 1, 0.637401,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452722,-99) , 
3, 204.371, 0, 0, 0.49371,-99) , 
5, 390.68, 0, 0, 0.497428,-99) , 
6, 235.502, 0, 0, 0.505817,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00843789);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693461,-99) , 
NN(
NN(
0, 
0, 
-1, 313.721, 0, 1, 0.56315,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453954,-99) , 
7, -1.02858, 0, 0, 0.494197,-99) , 
4, 0.063164, 0, 0, 0.502073,-99) , 
6, 278.284, 0, 0, 0.508328,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0120225);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 412.395, 0, 1, 0.66554,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477017,-99) , 
8, 1.04614, 0, 0, 0.561788,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458594,-99) , 
3, 204.397, 0, 0, 0.492284,-99) , 
5, 341.81, 0, 0, 0.497888,-99) , 
6, 249.041, 0, 0, 0.506457,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0109939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656578,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465617,-99) , 
3, 205.693, 0, 0, 0.496433,-99) , 
5, 370.639, 0, 0, 0.50044,-99) , 
6, 249.042, 0, 0, 0.508204,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00929272);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 452.678, 0, 1, 0.63142,-99) , 
NN(
NN(
0, 
0, 
-1, 2, 0, 1, 0.529281,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.487979,-99) , 
4, -0.0342705, 0, 0, 0.497262,-99) , 
6, 232.483, 0, 0, 0.505757,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
