// Class: ReadBDT_100_50_05
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_100_50_05
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : matthies
Date           : Mon Sep 10 18:22:16 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /nfs/dust/cms/user/matthies/Analysis_80x_v5/CMSSW_8_0_24_patch1/src/UHH2/BoostedSingleTop/tmva_comb
Training events: 463792
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
tmva_n_btags                  tmva_n_btags                  tmva_n_btags                  N of b-tags                                                     'I'    [1,6]
tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    tmva_deltaphi_bottomlepton    #Delta#phi(l,b)               rad                               'F'    [1.04904174805e-05,3.1415848732]
tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    tmva_deltaphi_bottomtoptag    #Delta#phi(t,b)               rad                               'F'    [2.80514359474e-06,3.14159035683]
tmva_pseudotop_mass           tmva_pseudotop_mass           tmva_pseudotop_mass           l#nub mass                    GeV                               'F'    [87.0424880981,6687.15380859]
tmva_ptbalance                tmva_ptbalance                tmva_ptbalance                pT balance                                                      'F'    [-0.998895287514,4.64822101593]
tmva_wass_pt                  tmva_wass_pt                  tmva_wass_pt                  asso. W pT                    GeV                               'F'    [0.287396162748,2188.19360352]
tmva_lepton_pt                tmva_lepton_pt                tmva_lepton_pt                lepton pT                     GeV                               'F'    [50.0000190735,1194.46325684]
tmva_lepton_eta               tmva_lepton_eta               tmva_lepton_eta               lepton #eta                                                     'F'    [-2.39999055862,2.39996170998]
tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   tmva_deltaphi_leptonnextjet   #Delta#phi(l,jet)             rad                               'F'    [4.58955764771e-06,3.14143514633]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_100_50_05Node
   
#ifndef BDT_100_50_05Node__def
#define BDT_100_50_05Node__def
   
class BDT_100_50_05Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_100_50_05Node ( BDT_100_50_05Node* left,BDT_100_50_05Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_100_50_05Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_100_50_05Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_100_50_05Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_100_50_05Node*   fLeft;     // pointer to the left daughter node
   BDT_100_50_05Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_100_50_05Node::~BDT_100_50_05Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_100_50_05Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_100_50_05Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_100_50_05 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_100_50_05( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_100_50_05" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tmva_n_btags", "tmva_deltaphi_bottomlepton", "tmva_deltaphi_bottomtoptag", "tmva_pseudotop_mass", "tmva_ptbalance", "tmva_wass_pt", "tmva_lepton_pt", "tmva_lepton_eta", "tmva_deltaphi_leptonnextjet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_100_50_05() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_100_50_05Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_100_50_05::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_100_50_05Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_100_50_05Node*)current->GetRight();
         else current=(BDT_100_50_05Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_100_50_05::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.431707595917032);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 137.24, 0, 1, 0.760187,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430953,-99) , 
5, 257.061, 0, 0, 0.513255,-99) , 
NN(
0, 
0, 
-1, 1.94487, 1, -1, 0.268398,-99) , 
3, 248.038, 0, 0, 0.376597,-99) , 
8, 1.64547, 0, 0, 0.502937,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.323625);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 159, 0, 1, 0.683502,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411852,-99) , 
6, 138.498, 0, 0, 0.455814,-99) , 
NN(
0, 
0, 
-1, 208.284, 0, -1, 0.297758,-99) , 
1, 1.04722, 0, 0, 0.385694,-99) , 
8, 1.34599, 0, 0, 0.507021,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.29894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 158.999, 0, 1, 0.69466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445393,-99) , 
4, -0.235318, 0, 0, 0.496601,-99) , 
8, 1.04711, 0, 0, 0.621938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502025,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.30639,-99) , 
2, 1.34645, 1, 0, 0.357613,-99) , 
3, 248.09, 0, 0, 0.508765,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.253596);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 154.452, 0, 1, 0.688542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477811,-99) , 
1, 1.64553, 0, 0, 0.650657,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458387,-99) , 
8, 0.897476, 0, 0, 0.51774,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.339751,-99) , 
3, 241.001, 0, 0, 0.429242,-99) , 
4, -0.0786804, 0, 0, 0.499673,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.20795);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 159.013, 0, 1, 0.63716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41079,-99) , 
3, 222.849, 0, 0, 0.484513,-99) , 
8, 1.19656, 0, 0, 0.587136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474866,-99) , 
3, 387.057, 0, 0, 0.504081,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.357053,-99) , 
3, 240.708, 0, 0, 0.426436,-99) , 
4, -0.190171, 0, 0, 0.505384,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.165332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 158.956, 0, 1, 0.614901,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487891,-99) , 
2, 1.04721, 0, 0, 0.516458,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.400347,-99) , 
3, 241.001, 0, 0, 0.458818,-99) , 
4, -0.0797723, 0, 0, 0.508264,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.15663);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00408789, 0, 1, 0.605781,-99) , 
NN(
NN(
0, 
0, 
-1, 1.19678, 0, 1, 0.540786,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.408034,-99) , 
3, 239.737, 0, 0, 0.47305,-99) , 
8, 1.79511, 0, 0, 0.509851,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.127062);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.688955,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490284,-99) , 
6, 112.281, 0, 0, 0.527541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376415,-99) , 
0, 2, 1, 0, 0.448752,-99) , 
3, 249.153, 0, 0, 0.491563,-99) , 
6, 213.495, 0, 0, 0.509308,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.114369);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 224.477, 0, 1, 0.550817,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458751,-99) , 
4, -0.283447, 0, 0, 0.485577,-99) , 
NN(
0, 
0, 
-1, 195.35, 0, -1, 0.392925,-99) , 
0, 2, 1, 0, 0.440949,-99) , 
3, 248.981, 0, 0, 0.503476,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.11973);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648347,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473896,-99) , 
8, 1.04711, 0, 0, 0.518026,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.43261,-99) , 
3, 223.826, 0, 0, 0.485801,-99) , 
6, 206.668, 0, 0, 0.501985,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0980819);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645291,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495974,-99) , 
2, 1.0472, 0, 0, 0.517455,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.429469,-99) , 
3, 213.585, 0, 0, 0.487325,-99) , 
6, 213.495, 0, 0, 0.501256,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0910672);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0360784, 0, 1, 0.577617,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487285,-99) , 
1, 2.54317, 1, 0, 0.534832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436082,-99) , 
3, 206.77, 0, 0, 0.472101,-99) , 
3, 401.333, 0, 0, 0.483475,-99) , 
8, 1.94465, 0, 0, 0.505938,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.064054);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557727,-99) , 
NN(
0, 
0, 
-1, 0.598453, 0, -1, 0.483354,-99) , 
4, 0.0218788, 0, 0, 0.493998,-99) , 
6, 213.495, 0, 0, 0.505935,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0609464);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660809,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46013,-99) , 
1, 1.04724, 0, 0, 0.491718,-99) , 
4, 0.0329277, 0, 0, 0.502125,-99) , 
6, 238.352, 0, 0, 0.511502,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0760582);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476828,-99) , 
6, 93.62, 0, 0, 0.504138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424242,-99) , 
0, 2, 1, 0, 0.460475,-99) , 
1, 0.748004, 0, 0, 0.495653,-99) , 
4, 0.0806366, 0, 0, 0.507926,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0779298);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648072,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460849,-99) , 
5, 226.412, 0, 0, 0.502532,-99) , 
6, 158.998, 0, 0, 0.544366,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454913,-99) , 
7, 1.0287, 1, 0, 0.493939,-99) , 
NN(
0, 
0, 
-1, 2, 1, -1, 0.444274,-99) , 
1, 0.748015, 0, 0, 0.480601,-99) , 
8, 1.49589, 0, 0, 0.503146,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.062654);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476894,-99) , 
3, 401.333, 0, 0, 0.483132,-99) , 
8, 1.9447, 0, 0, 0.493109,-99) , 
4, 0.0797205, 0, 0, 0.504284,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0458129);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591258,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524685,-99) , 
NN(
0, 
0, 
-1, -1.0287, 0, -1, 0.485397,-99) , 
8, 2.09383, 0, 0, 0.49273,-99) , 
6, 213.496, 0, 0, 0.501171,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0436251);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588991,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496056,-99) , 
6, 204.115, 0, 0, 0.500821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44156,-99) , 
7, -1.25711, 0, 0, 0.494249,-99) , 
4, 0.0798959, 0, 0, 0.504492,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0670038);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587597,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471912,-99) , 
3, 205.099, 0, 0, 0.505791,-99) , 
NN(
0, 
0, 
-1, 0.598416, 0, -1, 0.449303,-99) , 
7, -1.02858, 0, 0, 0.496387,-99) , 
5, 355.511, 0, 0, 0.504864,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0436325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588189,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459119,-99) , 
5, 118.693, 0, 0, 0.503969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429466,-99) , 
2, 0.8977, 0, 0, 0.464482,-99) , 
7, 1.25705, 1, 0, 0.499279,-99) , 
5, 355.511, 0, 0, 0.507584,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0488447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562369,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48476,-99) , 
2, 1.0472, 0, 0, 0.499161,-99) , 
NN(
0, 
0, 
-1, 0.897647, 0, -1, 0.44461,-99) , 
7, 1.25687, 1, 0, 0.492799,-99) , 
4, 0.0767459, 0, 0, 0.500572,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0548663);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463903,-99) , 
1, 0.448829, 0, 0, 0.513622,-99) , 
NN(
0, 
0, 
-1, -1.56191, 0, -1, 0.468712,-99) , 
7, -0.800008, 0, 0, 0.503678,-99) , 
6, 213.495, 0, 0, 0.509897,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0506822);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595896,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468447,-99) , 
7, 0.800001, 1, 0, 0.501577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423674,-99) , 
5, 110.917, 0, 0, 0.49592,-99) , 
5, 385.708, 0, 0, 0.502442,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0792831);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436131,-99) , 
8, 1.19674, 0, 0, 0.533272,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489627,-99) , 
3, 309.75, 0, 0, 0.50585,-99) , 
NN(
0, 
0, 
-1, 381.9, 1, -1, 0.470397,-99) , 
2, 0.748002, 0, 0, 0.490971,-99) , 
6, 158.997, 0, 0, 0.499697,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0539549);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606559,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484338,-99) , 
6, 123.754, 0, 0, 0.517149,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443204,-99) , 
5, 258.001, 1, 0, 0.491547,-99) , 
8, 1.49579, 0, 0, 0.500289,-99) , 
5, 386.19, 0, 0, 0.507187,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0562607);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590878,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487379,-99) , 
6, 136.715, 0, 0, 0.511386,-99) , 
NN(
0, 
0, 
-1, 145.386, 1, -1, 0.478266,-99) , 
8, 1.49512, 0, 0, 0.489718,-99) , 
6, 232.101, 0, 0, 0.496093,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0691867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.54318, 1, 1, 0.565131,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492094,-99) , 
0, 2, 0, 0, 0.506753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428552,-99) , 
0, 2, 1, 0, 0.48197,-99) , 
3, 213.484, 0, 0, 0.498324,-99) , 
5, 345.041, 0, 0, 0.505405,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.053437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474663,-99) , 
6, 96.7077, 0, 0, 0.497128,-99) , 
6, 158.998, 0, 0, 0.527272,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443457,-99) , 
5, 111.605, 0, 0, 0.495788,-99) , 
NN(
0, 
0, 
-1, 0.897605, 0, -1, 0.461902,-99) , 
5, 259.078, 1, 0, 0.487559,-99) , 
8, 1.49592, 0, 0, 0.501402,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0565387);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488856,-99) , 
6, 96.7021, 0, 0, 0.502964,-99) , 
6, 159, 0, 0, 0.525103,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469922,-99) , 
0, 2, 1, 0, 0.494938,-99) , 
NN(
0, 
0, 
-1, 0.897628, 0, -1, 0.466867,-99) , 
6, 97.0878, 1, 0, 0.481205,-99) , 
8, 1.49589, 0, 0, 0.496635,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0535355);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498924,-99) , 
4, -0.137026, 0, 0, 0.507382,-99) , 
5, 280.512, 0, 0, 0.528462,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470362,-99) , 
3, 200.265, 0, 0, 0.492703,-99) , 
NN(
0, 
0, 
-1, 273.392, 1, -1, 0.476767,-99) , 
2, 0.8976, 0, 0, 0.486532,-99) , 
8, 1.49593, 0, 0, 0.501243,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0422937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567161,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479225,-99) , 
7, 1.09392, 1, 0, 0.508814,-99) , 
NN(
0, 
0, 
-1, 0.897656, 0, -1, 0.47365,-99) , 
7, -1.02836, 0, 0, 0.503123,-99) , 
5, 385.164, 0, 0, 0.507137,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0377686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593638,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49894,-99) , 
8, 1.4952, 0, 0, 0.509037,-99) , 
NN(
0, 
0, 
-1, 231.608, 1, -1, 0.462402,-99) , 
7, -1.02852, 0, 0, 0.501615,-99) , 
5, 403.733, 0, 0, 0.506413,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0411182);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494083,-99) , 
2, 0.897599, 0, 0, 0.509005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448506,-99) , 
1, 1.19676, 0, 0, 0.479241,-99) , 
5, 136.249, 0, 0, 0.504754,-99) , 
6, 237.806, 0, 0, 0.509233,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0534514);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555363,-99) , 
NN(
NN(
0, 
0, 
-1, 2, 0, 1, 0.515687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444246,-99) , 
0, 2, 1, 0, 0.485774,-99) , 
3, 208.81, 0, 0, 0.505785,-99) , 
3, 597.478, 0, 0, 0.508952,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0322236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542313,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486683,-99) , 
0, 2, 1, 0, 0.507922,-99) , 
NN(
0, 
0, 
-1, 1.19679, 0, -1, 0.490377,-99) , 
6, 101.372, 1, 0, 0.499426,-99) , 
4, 0.0940732, 0, 0, 0.503453,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0312201);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550142,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460559,-99) , 
7, -1.48571, 0, 0, 0.503571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445435,-99) , 
5, 102.445, 0, 0, 0.500043,-99) , 
5, 356.055, 0, 0, 0.504602,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.052108);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487532,-99) , 
1, 1.93774, 1, 0, 0.494468,-99) , 
0, 2, 0, 0, 0.506002,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468379,-99) , 
3, 176.633, 1, 0, 0.493396,-99) , 
NN(
0, 
0, 
-1, 150.301, 1, -1, 0.457832,-99) , 
6, 101.372, 1, 0, 0.47782,-99) , 
1, 1.1968, 0, 0, 0.49779,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0358037);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542785,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499346,-99) , 
5, 109.372, 0, 0, 0.528951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473026,-99) , 
3, 248.038, 0, 0, 0.488302,-99) , 
4, -0.537913, 1, 0, 0.494143,-99) , 
4, 0.0767459, 0, 0, 0.499576,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0220442);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561714,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499423,-99) , 
2, 2.84239, 0, 0, 0.503885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458534,-99) , 
5, 109.884, 0, 0, 0.500658,-99) , 
5, 383.886, 0, 0, 0.504611,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0268288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542269,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493637,-99) , 
0, 2, 0, 0, 0.50091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478572,-99) , 
5, 118.422, 0, 0, 0.498822,-99) , 
6, 213.495, 0, 0, 0.502463,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0544586);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456431,-99) , 
8, 0.897559, 0, 0, 0.537792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487317,-99) , 
8, 1.19635, 1, 0, 0.505855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468323,-99) , 
2, 2.84239, 1, 0, 0.501394,-99) , 
5, 312.845, 0, 0, 0.507104,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0300319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561214,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497096,-99) , 
2, 1.1968, 0, 0, 0.506145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458621,-99) , 
5, 110.916, 0, 0, 0.502672,-99) , 
5, 385.708, 0, 0, 0.506431,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0480867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555542,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487567,-99) , 
1, 2.39731, 0, 0, 0.508128,-99) , 
6, 154.454, 0, 0, 0.5223,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486296,-99) , 
0, 2, 1, 0, 0.506807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433993,-99) , 
2, 1.0472, 0, 0, 0.472117,-99) , 
5, 258.5, 1, 0, 0.498421,-99) , 
8, 1.49588, 0, 0, 0.506692,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.026617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518629,-99) , 
NN(
0, 
0, 
-1, -0.0984708, 1, -1, 0.490794,-99) , 
8, 2.09383, 0, 0, 0.496051,-99) , 
5, 385.164, 0, 0, 0.499323,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0340405);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 104.511, 0, 1, 0.532733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498162,-99) , 
4, -0.523568, 1, 0, 0.502904,-99) , 
8, 1.49579, 0, 0, 0.513123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458805,-99) , 
7, 1.4857, 1, 0, 0.509125,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0538157);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549193,-99) , 
NN(
NN(
0, 
0, 
-1, 2, 0, 1, 0.515257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437116,-99) , 
3, 144.673, 1, 0, 0.476276,-99) , 
3, 179.921, 0, 0, 0.50704,-99) , 
3, 573.162, 0, 0, 0.510156,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0273953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487505,-99) , 
5, 232.709, 1, 0, 0.499636,-99) , 
5, 402.758, 0, 0, 0.502348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460344,-99) , 
5, 105.185, 0, 0, 0.499827,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0273698);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498546,-99) , 
3, 152.968, 1, 0, 0.504011,-99) , 
3, 548.523, 0, 0, 0.508133,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430976,-99) , 
2, 0.89758, 0, 0, 0.467175,-99) , 
7, -1.25708, 0, 0, 0.503606,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0138273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53318,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532669,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47613,-99) , 
8, 2.39294, 1, 0, 0.497597,-99) , 
2, 2.99199, 0, 0, 0.499961,-99) , 
6, 213.43, 0, 0, 0.502721,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0277257);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538895,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495934,-99) , 
2, 2.69279, 0, 0, 0.500786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43331,-99) , 
8, 0.588607, 0, 0, 0.475182,-99) , 
4, -0.489821, 0, 0, 0.496571,-99) , 
6, 213.43, 0, 0, 0.500192,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0476033);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460721,-99) , 
8, 0.897557, 0, 0, 0.517834,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461938,-99) , 
5, 112.427, 0, 0, 0.500322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465523,-99) , 
0, 2, 0, 0, 0.478987,-99) , 
4, -0.133419, 1, 0, 0.493594,-99) , 
6, 154.446, 0, 0, 0.499175,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0483741);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474372,-99) , 
3, 229.615, 0, 0, 0.523079,-99) , 
NN(
0, 
0, 
-1, 1.25737, 1, -1, 0.494656,-99) , 
2, 0.897553, 0, 0, 0.504383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493195,-99) , 
2, 2.97576, 1, 0, 0.511121,-99) , 
NN(
0, 
0, 
-1, 95.5304, 1, -1, 0.451904,-99) , 
2, 2.79336, 0, 0, 0.482911,-99) , 
1, 0.897645, 0, 0, 0.499663,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0376188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.448797, 0, 1, 0.54289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480561,-99) , 
3, 248.919, 0, 0, 0.527486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490692,-99) , 
0, 2, 1, 0, 0.504784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475891,-99) , 
7, -1.25698, 0, 0, 0.501572,-99) , 
4, -0.0452661, 0, 0, 0.508163,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0501472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.107215, 0, 1, 0.550424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486091,-99) , 
8, 1.79506, 0, 0, 0.501226,-99) , 
0, 2, 0, 0, 0.51345,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487389,-99) , 
2, 0.44879, 0, 0, 0.513871,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467218,-99) , 
1, 2.09433, 0, 0, 0.480046,-99) , 
3, 339.524, 0, 0, 0.488132,-99) , 
4, -0.192164, 0, 0, 0.500524,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0192834);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527081,-99) , 
NN(
0, 
0, 
-1, -1.48552, 0, -1, 0.493131,-99) , 
2, 2.99198, 0, 0, 0.495285,-99) , 
6, 237.806, 0, 0, 0.497465,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0319814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 158.998, 0, 1, 0.517106,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442884,-99) , 
6, 179.522, 1, 0, 0.498121,-99) , 
8, 1.19675, 0, 0, 0.506595,-99) , 
NN(
0, 
0, 
-1, 2.24401, 1, -1, 0.469046,-99) , 
7, 1.2571, 1, 0, 0.502346,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0231042);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545152,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463764,-99) , 
5, 111.451, 0, 0, 0.500978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435996,-99) , 
5, 203.842, 1, 0, 0.469195,-99) , 
7, -1.25697, 0, 0, 0.497422,-99) , 
5, 386.144, 0, 0, 0.500477,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0303774);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.112882, 1, 1, 0.545867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495418,-99) , 
5, 204.948, 1, 0, 0.523925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492348,-99) , 
2, 2.69278, 0, 0, 0.496068,-99) , 
6, 213.496, 0, 0, 0.500037,-99) , 
8, 0.448764, 1, 0, 0.504664,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0529662);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477247,-99) , 
3, 214.072, 0, 0, 0.540544,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49372,-99) , 
2, 1.34632, 0, 0, 0.50216,-99) , 
0, 2, 0, 0, 0.511997,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530624,-99) , 
NN(
0, 
0, 
-1, -0.30721, 0, -1, 0.468124,-99) , 
7, -0.571431, 1, 0, 0.487002,-99) , 
1, 0.748003, 0, 0, 0.507522,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0307141);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530248,-99) , 
NN(
NN(
0, 
0, 
-1, 88.9117, 1, 1, 0.526095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491562,-99) , 
2, 2.69279, 0, 0, 0.496542,-99) , 
8, 0.448565, 1, 0, 0.502301,-99) , 
6, 213.43, 0, 0, 0.504622,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0378226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 158.998, 0, 1, 0.524553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476506,-99) , 
5, 136.362, 0, 0, 0.50537,-99) , 
8, 1.34633, 0, 0, 0.512843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47225,-99) , 
7, 1.48568, 1, 0, 0.509785,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0432664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.18217, 0, 1, 0.533676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486597,-99) , 
2, 0.897605, 0, 0, 0.505257,-99) , 
7, 0.364614, 1, 0, 0.514454,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496121,-99) , 
0, 2, 0, 0, 0.508269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431611,-99) , 
7, -0.767287, 1, 0, 0.469186,-99) , 
2, 2.39358, 1, 0, 0.498217,-99) , 
7, -0.114299, 0, 0, 0.507139,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0443015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 313.457, 0, 1, 0.512527,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447573,-99) , 
4, -0.480232, 0, 0, 0.511966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447821,-99) , 
5, 248.69, 1, 0, 0.494542,-99) , 
8, 0.598373, 0, 0, 0.507669,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0396023);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.111611, 1, 1, 0.54293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469876,-99) , 
7, -1.25705, 0, 0, 0.501693,-99) , 
5, 308.793, 0, 0, 0.508855,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484107,-99) , 
2, 0.448821, 1, 0, 0.497469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450789,-99) , 
5, 257.573, 1, 0, 0.485674,-99) , 
8, 0.747947, 0, 0, 0.500773,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0346477);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498008,-99) , 
5, 193.462, 1, 0, 0.529119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491194,-99) , 
6, 158.998, 0, 0, 0.498305,-99) , 
8, 0.747967, 1, 0, 0.506307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516718,-99) , 
NN(
0, 
0, 
-1, 198.911, 0, -1, 0.481025,-99) , 
7, 1.02816, 0, 0, 0.486993,-99) , 
1, 1.79522, 0, 0, 0.498318,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0262148);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531355,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496848,-99) , 
1, 2.54315, 1, 0, 0.507983,-99) , 
4, 0.0907475, 0, 0, 0.510172,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465927,-99) , 
2, 0.897595, 0, 0, 0.485862,-99) , 
7, -1.25715, 0, 0, 0.507511,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0456611);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482053,-99) , 
2, 0.299188, 1, 0, 0.489056,-99) , 
0, 2, 0, 0, 0.499204,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488048,-99) , 
8, 0.582724, 1, 0, 0.502047,-99) , 
NN(
0, 
0, 
-1, 248.004, 0, -1, 0.458209,-99) , 
0, 2, 1, 0, 0.477296,-99) , 
1, 1.49601, 0, 0, 0.491423,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0400561);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520567,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486402,-99) , 
8, 1.04711, 1, 0, 0.503077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452175,-99) , 
8, 1.19644, 0, 0, 0.484904,-99) , 
6, 138.72, 1, 0, 0.498402,-99) , 
4, 0.0786287, 0, 0, 0.5007,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0247835);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525653,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491899,-99) , 
8, 1.45215, 0, 0, 0.498684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47328,-99) , 
8, 2.42909, 1, 0, 0.496126,-99) , 
8, 0.149598, 1, 0, 0.49802,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0276001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490268,-99) , 
7, -0.734487, 0, 0, 0.506555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473448,-99) , 
7, 1.48575, 1, 0, 0.504103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476178,-99) , 
1, 0.448839, 0, 0, 0.501481,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0430504);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492074,-99) , 
2, 0.598411, 0, 0, 0.530665,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473748,-99) , 
5, 276.159, 1, 0, 0.51324,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46884,-99) , 
0, 2, 1, 0, 0.489054,-99) , 
1, 2.39361, 0, 0, 0.498569,-99) , 
5, 340.474, 0, 0, 0.502172,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0360978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48504,-99) , 
3, 198.566, 0, 0, 0.517194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492123,-99) , 
1, 1.94519, 1, 0, 0.499944,-99) , 
0, 2, 0, 0, 0.505185,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462019,-99) , 
8, 0.128222, 1, 0, 0.483235,-99) , 
8, 0.299182, 0, 0, 0.502661,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0358953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496977,-99) , 
8, 1.04705, 1, 0, 0.505471,-99) , 
6, 213.495, 0, 0, 0.50861,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473237,-99) , 
3, 159.1, 1, 0, 0.504932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45144,-99) , 
3, 213.147, 1, 0, 0.488526,-99) , 
1, 0.89762, 0, 0, 0.504121,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0233987);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525066,-99) , 
NN(
NN(
0, 
0, 
-1, 2.5432, 0, 1, 0.507608,-99) , 
NN(
0, 
0, 
-1, 0.747992, 0, -1, 0.477067,-99) , 
5, 285.145, 1, 0, 0.502468,-99) , 
4, 0.0802795, 0, 0, 0.504761,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0523929);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.823162, 0, 1, 0.510326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473413,-99) , 
7, 1.25711, 1, 0, 0.506047,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460457,-99) , 
5, 205.332, 0, 0, 0.509647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449743,-99) , 
3, 152.037, 1, 0, 0.46896,-99) , 
3, 223.533, 0, 0, 0.481895,-99) , 
1, 1.7952, 0, 0, 0.496125,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0241084);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494485,-99) , 
1, 0.448785, 0, 0, 0.50751,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486864,-99) , 
2, 0.448801, 1, 0, 0.491803,-99) , 
8, 0.448763, 1, 0, 0.494847,-99) , 
6, 238.351, 0, 0, 0.497214,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.044775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479586,-99) , 
4, -0.172967, 1, 0, 0.492627,-99) , 
6, 206.669, 0, 0, 0.498884,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479549,-99) , 
4, -0.346278, 0, 0, 0.493507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418006,-99) , 
5, 273.736, 1, 0, 0.47858,-99) , 
8, 0.747945, 0, 0, 0.491901,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0547873);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 208.293, 0, 1, 0.556378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456739,-99) , 
3, 153.188, 1, 0, 0.482808,-99) , 
3, 224.655, 0, 0, 0.513759,-99) , 
NN(
NN(
0, 
0, 
-1, 0.570509, 0, 1, 0.52014,-99) , 
NN(
0, 
0, 
-1, 2.78542, 0, -1, 0.483688,-99) , 
1, 1.64564, 1, 0, 0.49293,-99) , 
0, 2, 0, 0, 0.499439,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0409233);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497881,-99) , 
7, 0.114329, 1, 0, 0.515558,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486574,-99) , 
8, 1.01854, 0, 0, 0.516357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471941,-99) , 
8, 0.740826, 1, 0, 0.488184,-99) , 
5, 276.769, 0, 0, 0.493905,-99) , 
8, 1.9447, 0, 0, 0.499091,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0363913);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467985,-99) , 
8, 1.19669, 0, 0, 0.496986,-99) , 
0, 2, 0, 0, 0.507874,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489436,-99) , 
4, -0.510889, 1, 0, 0.497462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461153,-99) , 
1, 0.660117, 0, 0, 0.477511,-99) , 
2, 2.69278, 1, 0, 0.492265,-99) , 
4, -0.147638, 0, 0, 0.498765,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.046145);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.0439423, 0, 1, 0.518984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481203,-99) , 
8, 0.747967, 0, 0, 0.509229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477268,-99) , 
3, 152.337, 1, 0, 0.486734,-99) , 
3, 360.302, 0, 0, 0.493044,-99) , 
1, 2.54317, 0, 0, 0.498634,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0213297);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528254,-99) , 
NN(
0, 
0, 
-1, 1.51741, 0, -1, 0.491681,-99) , 
1, 0.299252, 1, 0, 0.494032,-99) , 
5, 386.19, 0, 0, 0.496051,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0256879);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 336.616, 0, 1, 0.511015,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523585,-99) , 
NN(
0, 
0, 
-1, 0.212189, 1, -1, 0.486307,-99) , 
7, 1.02841, 0, 0, 0.49246,-99) , 
8, 0.897533, 0, 0, 0.503156,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0353546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5277,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480624,-99) , 
3, 208.852, 0, 0, 0.50088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44294,-99) , 
3, 210.147, 1, 0, 0.468384,-99) , 
4, -0.467162, 0, 0, 0.495221,-99) , 
3, 597.517, 0, 0, 0.497275,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.052041);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543428,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479506,-99) , 
5, 209.335, 1, 0, 0.491678,-99) , 
2, 0.897571, 0, 0, 0.504245,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471089,-99) , 
1, 0.705301, 1, 0, 0.496204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436542,-99) , 
6, 143.903, 1, 0, 0.484814,-99) , 
1, 1.34642, 0, 0, 0.49799,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0386068);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496085,-99) , 
8, 1.64547, 1, 0, 0.515029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47202,-99) , 
1, 0.748039, 0, 0, 0.507679,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480755,-99) , 
5, 192.647, 0, 0, 0.505488,-99) , 
NN(
0, 
0, 
-1, 0.897585, 0, -1, 0.482622,-99) , 
0, 2, 0, 0, 0.489809,-99) , 
7, 0.114329, 0, 0, 0.498175,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0380386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537887,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488007,-99) , 
7, 1.02841, 1, 0, 0.506101,-99) , 
5, 315.432, 0, 0, 0.511618,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476269,-99) , 
3, 227.697, 1, 0, 0.499539,-99) , 
NN(
0, 
0, 
-1, -0.234586, 0, -1, 0.474487,-99) , 
6, 101.372, 1, 0, 0.488183,-99) , 
8, 1.04711, 0, 0, 0.500214,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0377897);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48599,-99) , 
3, 213.281, 0, 0, 0.522625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494888,-99) , 
4, -0.185129, 1, 0, 0.504439,-99) , 
0, 2, 0, 0, 0.509624,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484337,-99) , 
4, -0.432965, 0, 0, 0.504681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466785,-99) , 
6, 138.725, 1, 0, 0.495404,-99) , 
8, 0.598372, 0, 0, 0.505868,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.022029);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534205,-99) , 
NN(
NN(
0, 
0, 
-1, 1.13979, 0, 1, 0.510895,-99) , 
NN(
0, 
0, 
-1, 1.64552, 1, -1, 0.491457,-99) , 
4, -0.102225, 0, 0, 0.498519,-99) , 
2, 2.99199, 0, 0, 0.500842,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0224681);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552243,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498802,-99) , 
8, 1.00439, 0, 0, 0.505464,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480401,-99) , 
0, 2, 0, 0, 0.487732,-99) , 
7, -0.799923, 0, 0, 0.501541,-99) , 
8, 0.149593, 1, 0, 0.504836,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0421757);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477675,-99) , 
6, 143.167, 0, 0, 0.497948,-99) , 
2, 0.448768, 0, 0, 0.513758,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491553,-99) , 
3, 241.279, 1, 0, 0.502136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451612,-99) , 
3, 147.212, 1, 0, 0.478734,-99) , 
3, 177.142, 0, 0, 0.496568,-99) , 
3, 401.627, 0, 0, 0.500419,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0198057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523889,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488217,-99) , 
7, -0.549671, 0, 0, 0.499808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471928,-99) , 
7, 1.48569, 1, 0, 0.497744,-99) , 
2, 2.99199, 0, 0, 0.499393,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0430456);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.798954, 1, 1, 0.524007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476462,-99) , 
5, 273.478, 1, 0, 0.514719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536055,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474642,-99) , 
8, 1.96576, 0, 0, 0.486347,-99) , 
5, 336.592, 0, 0, 0.492557,-99) , 
8, 0.897565, 1, 0, 0.502131,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0303456);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546354,-99) , 
NN(
NN(
0, 
0, 
-1, 2.39356, 0, 1, 0.510149,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485782,-99) , 
4, -0.532885, 1, 0, 0.494119,-99) , 
4, -0.18629, 0, 0, 0.501415,-99) , 
5, 385.708, 0, 0, 0.504284,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0398842);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.04719, 0, 1, 0.515862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472479,-99) , 
3, 200.756, 0, 0, 0.495028,-99) , 
3, 257.436, 0, 0, 0.506316,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481333,-99) , 
7, 1.61166, 1, 0, 0.497243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47466,-99) , 
6, 154.447, 0, 0, 0.481139,-99) , 
7, 1.12654, 0, 0, 0.487238,-99) , 
7, 0.342873, 1, 0, 0.499046,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0304289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.19679, 0, 1, 0.514876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488723,-99) , 
2, 1.19682, 1, 0, 0.497568,-99) , 
3, 256.509, 0, 0, 0.506025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481581,-99) , 
8, 2.24388, 1, 0, 0.502316,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0425907);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467014,-99) , 
6, 97.0895, 1, 0, 0.494061,-99) , 
3, 309.823, 0, 0, 0.50383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479471,-99) , 
3, 190.188, 0, 0, 0.503937,-99) , 
NN(
0, 
0, 
-1, 1.19674, 0, -1, 0.483265,-99) , 
1, 1.64562, 1, 0, 0.488396,-99) , 
0, 2, 0, 0, 0.493252,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0316351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 313.802, 0, 1, 0.514524,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480163,-99) , 
1, 2.73923, 0, 0, 0.494602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445612,-99) , 
4, -0.415689, 0, 0, 0.48689,-99) , 
2, 0.598407, 0, 0, 0.5041,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0256404);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499938,-99) , 
8, 0.83314, 0, 0, 0.529203,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476091,-99) , 
6, 152.743, 1, 0, 0.503542,-99) , 
3, 425.975, 0, 0, 0.507368,-99) , 
NN(
0, 
0, 
-1, 0.343374, 0, -1, 0.489522,-99) , 
8, 1.94462, 1, 0, 0.503135,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_100_50_05::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_100_50_05::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
